"""[core:time] events: the time-bound rows of event entities, backfilled for v0.1.0 vaults

Revision ID: 0f7812a431dd
Revises: ce20505bf34f
Create Date: 2026-10-06 18:37:01.535146+00:00

v0.1.0 had event entities without time data. The backfill (decided 2026-10-06): every event gets
a home row on its dimension's prime timeline starting at absolute 0 (precision base) with an
instant end, importance 3 and no category, plus the end's dependency edge on its start.
"""
# Self-contained: never import ORM models or services here (persistence-and-migrations.md §3.2).

import json
import uuid
from collections.abc import Sequence
from datetime import UTC, datetime

import sqlalchemy as sa
from alembic import op

revision: str = "0f7812a431dd"
down_revision: str | None = "ce20505bf34f"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None

ZERO_POINT = {"anchor": {"kind": "absolute", "t": "0"}, "precision": "base", "approximate": False}
INSTANT = {"kind": "instant"}
ZERO_KEY = "00010"  # lore.chronology.numbers.sortable_key(0), frozen (time-model.md §2.3)


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "events",
        sa.Column("entity_id", sa.String(), nullable=False),
        sa.Column("timeline_id", sa.String(), nullable=False),
        sa.Column("overrides_id", sa.String(), nullable=True),
        sa.Column("start_spec", sa.JSON(), nullable=False),
        sa.Column("start_t", sa.String(), nullable=True),
        sa.Column("end_spec", sa.JSON(), nullable=False),
        sa.Column("end_t", sa.String(), nullable=True),
        sa.Column("time_status", sa.String(), nullable=True),
        sa.Column("importance", sa.Integer(), server_default=sa.text("3"), nullable=False),
        sa.Column("category", sa.String(), nullable=True),
        sa.Column("recurrence", sa.JSON(), nullable=True),
        sa.Column("series_start_t", sa.String(), nullable=True),
        sa.Column("series_end_t", sa.String(), nullable=True),
        sa.Column("series_entity_id", sa.String(), nullable=True),
        sa.Column("occurrence_key", sa.String(), nullable=True),
        sa.Column("occurrence_state", sa.String(), nullable=True),
        sa.Column("original_start_t", sa.String(), nullable=True),
        sa.Column("revision", sa.Integer(), server_default=sa.text("1"), nullable=False),
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("created_at", sa.String(), nullable=False),
        sa.Column("updated_at", sa.String(), nullable=False),
        sa.CheckConstraint("importance BETWEEN 1 AND 5", name=op.f("ck_events_importance")),
        sa.ForeignKeyConstraint(
            ["entity_id"],
            ["entities.id"],
            name=op.f("fk_events_entity_id_entities"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["overrides_id"],
            ["events.id"],
            name=op.f("fk_events_overrides_id_events"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["series_entity_id"],
            ["entities.id"],
            name=op.f("fk_events_series_entity_id_entities"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["timeline_id"],
            ["entities.id"],
            name=op.f("fk_events_timeline_id_entities"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_events")),
    )
    with op.batch_alter_table("events", schema=None) as batch_op:
        batch_op.create_index("ix_events_entity_id", ["entity_id"], unique=False)
        batch_op.create_index("ix_events_overrides_id", ["overrides_id"], unique=False)
        batch_op.create_index("ix_events_timeline_id_end_t", ["timeline_id", "end_t"], unique=False)
        batch_op.create_index(
            "ix_events_timeline_id_series_start_t",
            ["timeline_id", "series_start_t"],
            unique=False,
            sqlite_where=sa.text("recurrence IS NOT NULL"),
        )
        batch_op.create_index(
            "ix_events_timeline_id_start_t", ["timeline_id", "start_t"], unique=False
        )
        batch_op.create_index(
            "uq_events_series_entity_id_occurrence_key_timeline_id",
            ["series_entity_id", "occurrence_key", "timeline_id"],
            unique=True,
            sqlite_where=sa.text("series_entity_id IS NOT NULL"),
        )

    # ### end Alembic commands ###
    _backfill()


def _backfill() -> None:
    connection = op.get_bind()
    events = connection.execute(
        sa.text(
            "SELECT e.id, t.entity_id FROM entities e "
            "JOIN timelines t ON t.dimension_id = e.dimension_id AND t.is_prime "
            "WHERE e.kind = 'event' ORDER BY e.id"
        )
    ).all()
    now = datetime.now(UTC).isoformat(timespec="microseconds")
    for entity_id, prime in events:
        connection.execute(
            sa.text(
                "INSERT INTO events (id, entity_id, timeline_id, start_spec, start_t, end_spec, "
                "end_t, time_status, importance, revision, created_at, updated_at) VALUES "
                "(:id, :entity, :timeline, :start, :zero, :end, :zero, 'ok', 3, 1, :now, :now)"
            ),
            {
                "id": str(uuid.uuid7()),
                "entity": entity_id,
                "timeline": prime,
                "start": json.dumps(ZERO_POINT),
                "end": json.dumps(INSTANT),
                "zero": ZERO_KEY,
                "now": now,
            },
        )
        connection.execute(
            sa.text(
                "INSERT INTO time_dependencies (dependent_type, dependent_id, dependent_slot, "
                "target_kind, target_type, target_id, target_slot) "
                "VALUES ('event', :id, 'end', 'slot', 'event', :id, 'start')"
            ),
            {"id": entity_id},
        )


def downgrade() -> None:
    op.execute(
        "DELETE FROM time_dependencies WHERE dependent_type = 'event' OR target_type = 'event'"
    )
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("events", schema=None) as batch_op:
        batch_op.drop_index(
            "uq_events_series_entity_id_occurrence_key_timeline_id",
            sqlite_where=sa.text("series_entity_id IS NOT NULL"),
        )
        batch_op.drop_index("ix_events_timeline_id_start_t")
        batch_op.drop_index(
            "ix_events_timeline_id_series_start_t", sqlite_where=sa.text("recurrence IS NOT NULL")
        )
        batch_op.drop_index("ix_events_timeline_id_end_t")
        batch_op.drop_index("ix_events_overrides_id")
        batch_op.drop_index("ix_events_entity_id")

    op.drop_table("events")
    # ### end Alembic commands ###
