"""[core] consistency findings and suppressions

Revision ID: cef63815176d
Revises: 55c1c3bdb399
Create Date: 2026-10-07 21:01:26.651283+00:00
"""
# Self-contained: never import ORM models or services here (persistence-and-migrations.md §3.2).

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "cef63815176d"
down_revision: str | None = "55c1c3bdb399"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "consistency_findings",
        sa.Column("fingerprint", sa.String(), nullable=False),
        sa.Column("rule_id", sa.String(), nullable=False),
        sa.Column("certainty", sa.String(), nullable=False),
        sa.Column("message", sa.String(), nullable=False),
        sa.Column("timeline_id", sa.String(), nullable=True),
        sa.Column("data", sa.JSON(), server_default=sa.text("'{}'"), nullable=False),
        sa.Column("created_at", sa.String(), nullable=False),
        sa.Column("updated_at", sa.String(), nullable=False),
        sa.Column("id", sa.String(), nullable=False),
        sa.CheckConstraint(
            "certainty IN ('definite', 'possible')", name=op.f("ck_consistency_findings_certainty")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_consistency_findings")),
        sa.UniqueConstraint("fingerprint", name=op.f("uq_consistency_findings_fingerprint")),
    )
    with op.batch_alter_table("consistency_findings", schema=None) as batch_op:
        batch_op.create_index("ix_consistency_findings_rule_id", ["rule_id"], unique=False)

    op.create_table(
        "consistency_suppressions",
        sa.Column("fingerprint", sa.String(), nullable=False),
        sa.Column("rule_id", sa.String(), nullable=False),
        sa.Column("note", sa.String(), nullable=False),
        sa.Column("created_at", sa.String(), nullable=False),
        sa.PrimaryKeyConstraint("fingerprint", name=op.f("pk_consistency_suppressions")),
    )
    op.create_table(
        "consistency_finding_entities",
        sa.Column("finding_id", sa.String(), nullable=False),
        sa.Column("entity_id", sa.String(), nullable=False),
        sa.Column("position", sa.Integer(), server_default=sa.text("0"), nullable=False),
        sa.ForeignKeyConstraint(
            ["finding_id"],
            ["consistency_findings.id"],
            name=op.f("fk_consistency_finding_entities_finding_id_consistency_findings"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint(
            "finding_id", "entity_id", name=op.f("pk_consistency_finding_entities")
        ),
    )
    with op.batch_alter_table("consistency_finding_entities", schema=None) as batch_op:
        batch_op.create_index(
            "ix_consistency_finding_entities_entity_id", ["entity_id"], unique=False
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("consistency_finding_entities", schema=None) as batch_op:
        batch_op.drop_index("ix_consistency_finding_entities_entity_id")

    op.drop_table("consistency_finding_entities")
    op.drop_table("consistency_suppressions")
    with op.batch_alter_table("consistency_findings", schema=None) as batch_op:
        batch_op.drop_index("ix_consistency_findings_rule_id")

    op.drop_table("consistency_findings")
    # ### end Alembic commands ###
