"""[core:time] calendars: the extension table, backfilled for v0.1.0 vaults

Revision ID: ce20505bf34f
Revises: 39828513f6da
Create Date: 2026-10-05 19:58:14.698430+00:00

v0.1.0 had calendar entities without definitions. Each gets a minimal calendar (decided
2026-10-05): unnamed days of 86,400 s in years of 365 days, year 1 starting at t = 0 (their
dimensions were backfilled in seconds). Per dimension, the earliest calendar (preferring ones not
in the trash) becomes the default.
"""
# Self-contained: never import ORM models or services here (persistence-and-migrations.md §3.2).

import json
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "ce20505bf34f"
down_revision: str | None = "39828513f6da"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None

ALIGNMENT = "/regimes/0/alignment/at"
MINIMAL_CALENDAR = {
    "schema_version": 1,
    "levels": [
        {"id": "day", "label": "Day", "plural": "Days"},
        {"id": "year", "label": "Year", "plural": "Years"},
    ],
    "regimes": [
        {
            "id": "default",
            "name": "Default",
            "templates": {
                "day": {"level": "day", "uniform": {"count": "86400"}},
                "year": {"level": "year", "uniform": {"count": "365", "template": "day"}},
            },
            "top": {"pattern": {"kind": "fixed", "template": "year"}},
            "alignment": {
                "fields": {"year": "1"},
                "at": {"anchor": {"kind": "absolute", "t": "0"}, "precision": "year"},
            },
        }
    ],
}


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "calendars",
        sa.Column("entity_id", sa.String(), nullable=False),
        sa.Column("dimension_id", sa.String(), nullable=False),
        sa.Column("definition", sa.JSON(), nullable=False),
        sa.Column("definition_revision", sa.Integer(), server_default=sa.text("1"), nullable=False),
        sa.Column("resolved_anchors", sa.JSON(), server_default=sa.text("'{}'"), nullable=False),
        sa.Column("compile_status", sa.String(), nullable=False),
        sa.Column("compile_errors", sa.JSON(), server_default=sa.text("'[]'"), nullable=False),
        sa.ForeignKeyConstraint(
            ["dimension_id"],
            ["entities.id"],
            name=op.f("fk_calendars_dimension_id_entities"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["entity_id"],
            ["entities.id"],
            name=op.f("fk_calendars_entity_id_entities"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("entity_id", name=op.f("pk_calendars")),
    )
    with op.batch_alter_table("calendars", schema=None) as batch_op:
        batch_op.create_index("ix_calendars_dimension_id", ["dimension_id"], unique=False)

    # ### end Alembic commands ###
    _backfill()


def _backfill() -> None:
    connection = op.get_bind()
    calendars = connection.execute(
        sa.text(
            "SELECT c.id, c.dimension_id FROM entities c JOIN dimensions d "
            "ON d.entity_id = c.dimension_id WHERE c.kind = 'calendar' "
            "ORDER BY c.dimension_id, c.deleted_at IS NOT NULL, c.created_at, c.id"
        )
    ).all()
    defaults: dict[str, str] = {}
    for calendar_id, dimension_id in calendars:
        connection.execute(
            sa.text(
                "INSERT INTO calendars (entity_id, dimension_id, definition, resolved_anchors, "
                "compile_status) VALUES (:id, :dimension, :definition, :anchors, 'ok')"
            ),
            {
                "id": calendar_id,
                "dimension": dimension_id,
                "definition": json.dumps(MINIMAL_CALENDAR),
                "anchors": json.dumps({ALIGNMENT: "0"}),
            },
        )
        defaults.setdefault(dimension_id, calendar_id)
    for dimension_id, calendar_id in defaults.items():
        connection.execute(
            sa.text("UPDATE dimensions SET default_calendar_id = :c WHERE entity_id = :d"),
            {"c": calendar_id, "d": dimension_id},
        )


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("calendars", schema=None) as batch_op:
        batch_op.drop_index("ix_calendars_dimension_id")

    op.drop_table("calendars")
    # ### end Alembic commands ###
