"""[core:time] time_dependencies: the dependency graph of time slots (time-model.md §7.1)

Revision ID: 557b1fb3271d
Revises: 4926f8f608bc
Create Date: 2026-10-05 18:09:23.577938+00:00

Derived data: the table starts empty and is filled as slot specs are written (no time-bearing
records exist yet).
"""
# Self-contained: never import ORM models or services here (persistence-and-migrations.md §3.2).

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "557b1fb3271d"
down_revision: str | None = "4926f8f608bc"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "time_dependencies",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("dependent_type", sa.String(), nullable=False),
        sa.Column("dependent_id", sa.String(), nullable=False),
        sa.Column("dependent_slot", sa.String(), nullable=False),
        sa.Column("target_kind", sa.String(), nullable=False),
        sa.Column("target_type", sa.String(), nullable=True),
        sa.Column("target_id", sa.String(), nullable=True),
        sa.Column("target_slot", sa.String(), nullable=True),
        sa.Column("target_calendar_id", sa.String(), nullable=True),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_time_dependencies")),
    )
    with op.batch_alter_table("time_dependencies", schema=None) as batch_op:
        batch_op.create_index(
            "ix_time_dependencies_dependent",
            ["dependent_type", "dependent_id", "dependent_slot"],
            unique=False,
        )
        batch_op.create_index(
            "ix_time_dependencies_target", ["target_type", "target_id", "target_slot"], unique=False
        )
        batch_op.create_index(
            "ix_time_dependencies_target_calendar_id", ["target_calendar_id"], unique=False
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("time_dependencies", schema=None) as batch_op:
        batch_op.drop_index("ix_time_dependencies_target_calendar_id")
        batch_op.drop_index("ix_time_dependencies_target")
        batch_op.drop_index("ix_time_dependencies_dependent")

    op.drop_table("time_dependencies")
    # ### end Alembic commands ###
