"""[core:time] proposals: impact previews of calendar and recurrence-rule edits

Revision ID: 55c1c3bdb399
Revises: 5455146e2257
Create Date: 2026-10-07 19:26:56.673269+00:00
"""
# Self-contained: never import ORM models or services here (persistence-and-migrations.md §3.2).

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "55c1c3bdb399"
down_revision: str | None = "5455146e2257"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "proposals",
        sa.Column("kind", sa.String(), nullable=False),
        sa.Column("target_id", sa.String(), nullable=False),
        sa.Column("payload", sa.JSON(), nullable=False),
        sa.Column("impact", sa.JSON(), nullable=False),
        sa.Column("base_revision", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.String(), nullable=False),
        sa.Column("expires_at", sa.String(), nullable=False),
        sa.Column("id", sa.String(), nullable=False),
        sa.CheckConstraint("kind IN ('calendar', 'recurrence')", name=op.f("ck_proposals_kind")),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_proposals")),
    )
    with op.batch_alter_table("proposals", schema=None) as batch_op:
        batch_op.create_index("ix_proposals_expires_at", ["expires_at"], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("proposals", schema=None) as batch_op:
        batch_op.drop_index("ix_proposals_expires_at")

    op.drop_table("proposals")
    # ### end Alembic commands ###
