"""[core:time] covering indexes for the timeline window

Revision ID: 03bd5b15f0be
Revises: 0f7812a431dd
Create Date: 2026-10-06 22:02:01.938571+00:00
"""
# Self-contained: never import ORM models or services here (persistence-and-migrations.md §3.2).

from collections.abc import Sequence

from alembic import op

revision: str = "03bd5b15f0be"
down_revision: str | None = "0f7812a431dd"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("entities", schema=None) as batch_op:
        batch_op.create_index(
            "ix_entities_visibility",
            ["id", "kind", "deleted_at", "visibility", "dimension_id", "origin_timeline_id"],
            unique=False,
        )

    with op.batch_alter_table("events", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_events_timeline_id_start_t"))
        batch_op.create_index(
            "ix_events_window",
            ["timeline_id", "start_t", "end_t", "importance", "entity_id", "id"],
            unique=False,
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("events", schema=None) as batch_op:
        batch_op.drop_index("ix_events_window")
        batch_op.create_index(
            batch_op.f("ix_events_timeline_id_start_t"), ["timeline_id", "start_t"], unique=False
        )

    with op.batch_alter_table("entities", schema=None) as batch_op:
        batch_op.drop_index("ix_entities_visibility")

    # ### end Alembic commands ###
