"""[core:time] dimensions and timelines: extension tables, backfilled for v0.1.0 vaults

Revision ID: 39828513f6da
Revises: 557b1fb3271d
Create Date: 2026-10-05 18:37:04.452794+00:00

v0.1.0 had dimension and timeline entities without time data. The backfill (decided 2026-10-05):

- Every dimension gets the time spec second/seconds/s with D = 10^100.
- Per dimension, its earliest-created timeline (preferring ones not in the trash) becomes the
  prime timeline; a dimension without one gets a new prime named "Prime". The prime takes its
  dimension's trash state and visibility. Every other timeline entity of the dimension becomes a
  branch of the prime with branch point absolute 0 (it inherits nothing).
- The search documents of the primes follow (trash state, visibility; a new prime is indexed).
"""
# Self-contained: never import ORM models or services here (persistence-and-migrations.md §3.2).

import json
import uuid
from collections.abc import Sequence
from datetime import UTC, datetime

import sqlalchemy as sa
from alembic import op

BASE_UNIT = {"singular": "second", "plural": "seconds", "abbr": "s"}
GOOGOL = 10**100
ZERO_POINT = {"anchor": {"kind": "absolute", "t": "0"}, "precision": "base", "approximate": False}


def _key(n: int) -> str:
    """A frozen copy of ``lore.chronology.numbers.sortable_key`` (time-model.md §2.3)."""
    digits = str(n)
    return f"{len(digits):04d}{digits}"


revision: str = "39828513f6da"
down_revision: str | None = "557b1fb3271d"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "dimensions",
        sa.Column("entity_id", sa.String(), nullable=False),
        sa.Column("base_unit", sa.JSON(), nullable=False),
        sa.Column("duration", sa.String(), nullable=False),
        sa.Column("default_calendar_id", sa.String(), nullable=True),
        sa.Column("present_spec", sa.JSON(), nullable=True),
        sa.Column("present_t", sa.String(), nullable=True),
        sa.Column("time_status", sa.String(), nullable=True),
        sa.ForeignKeyConstraint(
            ["default_calendar_id"],
            ["entities.id"],
            name=op.f("fk_dimensions_default_calendar_id_entities"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["entity_id"],
            ["entities.id"],
            name=op.f("fk_dimensions_entity_id_entities"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("entity_id", name=op.f("pk_dimensions")),
    )
    op.create_table(
        "timelines",
        sa.Column("entity_id", sa.String(), nullable=False),
        sa.Column("dimension_id", sa.String(), nullable=False),
        sa.Column("parent_timeline_id", sa.String(), nullable=True),
        sa.Column("is_prime", sa.Boolean(), server_default=sa.text("0"), nullable=False),
        sa.Column("branch_point_spec", sa.JSON(), nullable=True),
        sa.Column("branch_t", sa.String(), nullable=True),
        sa.Column("time_status", sa.String(), nullable=True),
        sa.ForeignKeyConstraint(
            ["dimension_id"],
            ["entities.id"],
            name=op.f("fk_timelines_dimension_id_entities"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["entity_id"],
            ["entities.id"],
            name=op.f("fk_timelines_entity_id_entities"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["parent_timeline_id"],
            ["timelines.entity_id"],
            name=op.f("fk_timelines_parent_timeline_id_timelines"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("entity_id", name=op.f("pk_timelines")),
    )
    with op.batch_alter_table("timelines", schema=None) as batch_op:
        batch_op.create_index("ix_timelines_dimension_id", ["dimension_id"], unique=False)
        batch_op.create_index(
            "ix_timelines_parent_timeline_id", ["parent_timeline_id"], unique=False
        )
        batch_op.create_index(
            "uq_timelines_prime_dimension_id",
            ["dimension_id"],
            unique=True,
            sqlite_where=sa.text("is_prime"),
        )

    # ### end Alembic commands ###
    _backfill()


def _backfill() -> None:
    connection = op.get_bind()
    dimensions = connection.execute(
        sa.text(
            "SELECT id, visibility, deleted_at FROM entities WHERE kind = 'dimension' ORDER BY id"
        )
    ).all()
    now = datetime.now(UTC).isoformat(timespec="microseconds")
    for dimension_id, visibility, deleted_at in dimensions:
        connection.execute(
            sa.text(
                "INSERT INTO dimensions (entity_id, base_unit, duration) VALUES (:id, :unit, :d)"
            ),
            {"id": dimension_id, "unit": json.dumps(BASE_UNIT), "d": _key(GOOGOL)},
        )
        timelines: Sequence[str] = (
            connection.execute(
                sa.text(
                    "SELECT id FROM entities WHERE kind = 'timeline' AND dimension_id = :id "
                    "ORDER BY deleted_at IS NOT NULL, created_at, id"
                ),
                {"id": dimension_id},
            )
            .scalars()
            .all()
        )
        if timelines:
            prime, *branches = timelines
        else:
            prime, branches = str(uuid.uuid7()), []
            connection.execute(
                sa.text(
                    "INSERT INTO entities (id, kind, dimension_id, name, slug, sort_name, "
                    "visibility, revision, created_at, updated_at) VALUES (:id, 'timeline', "
                    ":dimension, 'Prime', 'prime', 'prime', :visibility, 1, :now, :now)"
                ),
                {"id": prime, "dimension": dimension_id, "visibility": visibility, "now": now},
            )
            connection.execute(
                sa.text(
                    "INSERT INTO search_docs (doc_type, doc_id, entity_id, dimension_id, kind, "
                    "visibility, deleted, name) VALUES ('entity', :id, :id, :dimension, "
                    "'timeline', :visibility, 0, 'Prime')"
                ),
                {"id": prime, "dimension": dimension_id, "visibility": visibility},
            )
        connection.execute(
            sa.text(
                "UPDATE entities SET deleted_at = :deleted, visibility = :visibility WHERE id = :id"
            ),
            {"id": prime, "deleted": deleted_at, "visibility": visibility},
        )
        connection.execute(
            sa.text(
                "UPDATE search_docs SET deleted = :deleted, visibility = :visibility "
                "WHERE doc_type = 'entity' AND doc_id = :id"
            ),
            {"id": prime, "deleted": deleted_at is not None, "visibility": visibility},
        )
        connection.execute(
            sa.text(
                "INSERT INTO timelines (entity_id, dimension_id, is_prime) "
                "VALUES (:id, :dimension, 1)"
            ),
            {"id": prime, "dimension": dimension_id},
        )
        for branch in branches:
            connection.execute(
                sa.text(
                    "INSERT INTO timelines (entity_id, dimension_id, parent_timeline_id, is_prime, "
                    "branch_point_spec, branch_t, time_status) "
                    "VALUES (:id, :dimension, :prime, 0, :point, :t, 'ok')"
                ),
                {
                    "id": branch,
                    "dimension": dimension_id,
                    "prime": prime,
                    "point": json.dumps(ZERO_POINT),
                    "t": _key(0),
                },
            )


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("timelines", schema=None) as batch_op:
        batch_op.drop_index("uq_timelines_prime_dimension_id", sqlite_where=sa.text("is_prime"))
        batch_op.drop_index("ix_timelines_parent_timeline_id")
        batch_op.drop_index("ix_timelines_dimension_id")

    op.drop_table("timelines")
    op.drop_table("dimensions")
    # ### end Alembic commands ###
