// Generated by `make gen` (frontend/scripts/gen-api.ts) from the backend's OpenAPI document.
// Do not edit by hand: change the backend models, then run `make gen` and commit this file.

export interface paths {
    "/api/v1/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["system_health"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/meta": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Meta */
        get: operations["system_meta"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/vaults": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List */
        get: operations["vaults_list"];
        put?: never;
        /** Create */
        post: operations["vaults_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/vaults/{vault_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get */
        get: operations["vaults_get"];
        put?: never;
        post?: never;
        /**
         * Delete
         * @description Move the vault folder to the data directory's trash (it is never deleted).
         */
        delete: operations["vaults_delete"];
        options?: never;
        head?: never;
        /**
         * Update
         * @description Rename the vault (display name only; the folder keeps its name).
         */
        patch: operations["vaults_update"];
        trace?: never;
    };
    "/api/v1/vaults/{vault_id}/migrate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Migrate
         * @description Run pending migrations (after a pre-migration backup); a no-op for a current vault.
         */
        post: operations["vaults_migrate"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/vaults/{vault_id}/registry": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get */
        get: operations["registry_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/vaults/{vault_id}/modules/{module_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * Update
         * @description Enable (also enables dependencies) or disable (``409 module_has_dependents`` while
         *     dependents are enabled, unless ``cascade``) a module for this vault. Data is never deleted.
         */
        patch: operations["modules_update"];
        trace?: never;
    };
    "/api/v1/vaults/{vault_id}/entities": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Create
         * @description Create an entity of any kind, with its aliases, tags and kind extension data.
         */
        post: operations["entities_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/vaults/{vault_id}/entities/{entity_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get
         * @description The full entity (also when it is in the trash; ``deleted_at`` is then set).
         */
        get: operations["entities_get"];
        put?: never;
        post?: never;
        /**
         * Delete
         * @description Move to the trash, or purge from it (``409 conflict`` while the entity isn't trashed, has
         *     children or is still referenced).
         */
        delete: operations["entities_delete"];
        options?: never;
        head?: never;
        /**
         * Update
         * @description Change the members sent. ``409 revision_conflict`` (with ``context.current``) when
         *     ``revision`` isn't the current one; ``409 conflict`` while the entity is in the trash.
         */
        patch: operations["entities_update"];
        trace?: never;
    };
    "/api/v1/vaults/{vault_id}/entities/{entity_id}/restore": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Restore
         * @description Take the entity out of the trash.
         */
        post: operations["entities_restore"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * Affected
         * @description What a write changed, for client cache invalidation (``frontend.md`` §5).
         */
        Affected: {
            /** Entities */
            entities: string[];
            /** Dimensions */
            dimensions: string[];
            /** Time Changed */
            time_changed: boolean;
            /** Search Changed */
            search_changed: boolean;
        };
        /**
         * AliasIn
         * @description An alias. Send the ``id`` of an existing alias to keep it (and its history).
         */
        AliasIn: {
            id?: components["schemas"]["EntityId"] | null;
            alias: components["schemas"]["EntityName"];
            /** @default alias */
            alias_kind: components["schemas"]["AliasKind"];
            /** @default public */
            visibility: components["schemas"]["Visibility"];
        };
        /** @enum {string} */
        AliasKind: "alias" | "title" | "former_name" | "translation" | "nickname";
        /** AliasOut */
        AliasOut: {
            /** Id */
            id: string;
            /** Alias */
            alias: string;
            alias_kind: components["schemas"]["AliasKind"];
            visibility: components["schemas"]["Visibility"];
        };
        Color: string;
        /** EntityCreate */
        EntityCreate: {
            /**
             * Summary
             * @default
             */
            summary: string;
            body?: components["schemas"]["JsonObject"] | null;
            /**
             * Fields
             * @description Field values to set (merged into the stored values; null removes a value).
             */
            fields?: {
                [key: string]: unknown;
            };
            /**
             * Field Visibility
             * @description Per-field visibility overrides (merged; null removes an override).
             */
            field_visibility?: {
                [key: string]: components["schemas"]["Visibility"] | null;
            };
            icon?: components["schemas"]["Icon"] | null;
            color?: components["schemas"]["Color"] | null;
            sort_key?: components["schemas"]["SortKey"] | null;
            /** Aliases */
            aliases?: components["schemas"]["AliasIn"][];
            /** Tags */
            tags?: components["schemas"]["TagName"][];
            /** @description Kind extension data (e.g. a dimension's time spec, M3+). */
            ext?: components["schemas"]["JsonObject"] | null;
            /** Kind */
            kind: string;
            name: components["schemas"]["EntityName"];
            /** @description Home dimension; null = multiversal (if the kind allows it). */
            dimension_id?: components["schemas"]["EntityId"] | null;
            parent_id?: components["schemas"]["EntityId"] | null;
            /** @description Defaults to the vault's default visibility. */
            visibility?: components["schemas"]["Visibility"] | null;
        };
        /**
         * EntityDeleteResult
         * @description ``entity`` is the trashed entity, or null when it was purged.
         */
        EntityDeleteResult: {
            /** Id */
            id: string;
            /** Purged */
            purged: boolean;
            entity: components["schemas"]["EntityOut"] | null;
            affected: components["schemas"]["Affected"];
        };
        EntityId: string;
        EntityName: string;
        /**
         * EntityOut
         * @description A full entity. ``fields`` and ``field_visibility`` only hold the kind's active fields
         *     (values of archived fields and of disabled modules' fields are kept but not shown).
         */
        EntityOut: {
            /** Id */
            id: string;
            /** Kind */
            kind: string;
            /** Dimension Id */
            dimension_id: string | null;
            /** Origin Timeline Id */
            origin_timeline_id: string | null;
            /** Parent Id */
            parent_id: string | null;
            /** Name */
            name: string;
            /** Slug */
            slug: string;
            /** Summary */
            summary: string;
            body: components["schemas"]["JsonObject"] | null;
            /** Body Schema Version */
            body_schema_version: number | null;
            /** Fields */
            fields: {
                [key: string]: unknown;
            };
            /** Field Visibility */
            field_visibility: {
                [key: string]: components["schemas"]["Visibility"];
            };
            visibility: components["schemas"]["Visibility"];
            /** Icon */
            icon: string | null;
            /** Color */
            color: string | null;
            /** Cover Media Id */
            cover_media_id: string | null;
            /** Sort Key */
            sort_key: string | null;
            /** Aliases */
            aliases: components["schemas"]["AliasOut"][];
            /** Tags */
            tags: components["schemas"]["TagOut"][];
            ext: components["schemas"]["JsonObject"] | null;
            /** Revision */
            revision: number;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
            /** Deleted At */
            deleted_at: string | null;
        };
        /**
         * EntityUpdate
         * @description Only the members sent are changed. ``aliases`` and ``tags`` replace the whole list;
         *     ``fields`` and ``field_visibility`` are merged.
         */
        EntityUpdate: {
            /**
             * Summary
             * @default
             */
            summary: string;
            body?: components["schemas"]["JsonObject"] | null;
            /**
             * Fields
             * @description Field values to set (merged into the stored values; null removes a value).
             */
            fields?: {
                [key: string]: unknown;
            };
            /**
             * Field Visibility
             * @description Per-field visibility overrides (merged; null removes an override).
             */
            field_visibility?: {
                [key: string]: components["schemas"]["Visibility"] | null;
            };
            icon?: components["schemas"]["Icon"] | null;
            color?: components["schemas"]["Color"] | null;
            sort_key?: components["schemas"]["SortKey"] | null;
            /** Aliases */
            aliases?: components["schemas"]["AliasIn"][];
            /** Tags */
            tags?: components["schemas"]["TagName"][];
            /** @description Kind extension data (e.g. a dimension's time spec, M3+). */
            ext?: components["schemas"]["JsonObject"] | null;
            /**
             * Revision
             * @description The revision the edit is based on (409 on mismatch).
             */
            revision: number;
            name?: components["schemas"]["EntityName"] | null;
            dimension_id?: components["schemas"]["EntityId"] | null;
            parent_id?: components["schemas"]["EntityId"] | null;
            visibility?: components["schemas"]["Visibility"] | null;
        };
        /** EntityWriteResult */
        EntityWriteResult: {
            entity: components["schemas"]["EntityOut"];
            affected: components["schemas"]["Affected"];
        };
        /** FieldOptionOut */
        FieldOptionOut: {
            /** Key */
            key: string;
            /** Label */
            label: string;
            /** Color */
            color: string | null;
        };
        /** FieldOut */
        FieldOut: {
            /** Key */
            key: string;
            /** Label */
            label: string;
            /** Type */
            type: string;
            /** Options */
            options: components["schemas"]["FieldOptionOut"][];
            /** Multiple */
            multiple: boolean;
            /** Required */
            required: boolean;
            /** Temporal */
            temporal: boolean;
            /**
             * Default Visibility
             * @enum {string}
             */
            default_visibility: "public" | "spoiler" | "private";
            /** Section */
            section: string | null;
            /** Sort */
            sort: number;
            /** Help */
            help: string;
            /** Searchable */
            searchable: boolean;
            /** Archived */
            archived: boolean;
        };
        /** FieldTypeOut */
        FieldTypeOut: {
            /** Key */
            key: string;
            /** Label */
            label: string;
            /** Description */
            description: string;
        };
        /** GraphStyleOut */
        GraphStyleOut: {
            /** Color */
            color: string | null;
            /** Dashed */
            dashed: boolean;
            /** Weight */
            weight: number;
        };
        /** HealthResponse */
        HealthResponse: {
            /**
             * Status
             * @constant
             */
            status: "ok";
        };
        Icon: string;
        JsonObject: {
            [key: string]: unknown;
        };
        /** KindCapabilitiesOut */
        KindCapabilitiesOut: {
            /** Has Body */
            has_body: boolean;
            /** Can Be Multiversal */
            can_be_multiversal: boolean;
            /** Has Existence */
            has_existence: boolean;
            /** Can Have Worldline */
            can_have_worldline: boolean;
            /** Is Time Bound */
            is_time_bound: boolean;
            /** Is System */
            is_system: boolean;
        };
        /** KindOut */
        KindOut: {
            /** Key */
            key: string;
            /** Module */
            module: string;
            /** Label */
            label: string;
            /** Plural */
            plural: string;
            /** Icon */
            icon: string;
            /** Color */
            color: string;
            /** Description */
            description: string;
            /** Allowed Parents */
            allowed_parents: string[];
            capabilities: components["schemas"]["KindCapabilitiesOut"];
            /** Fields */
            fields: components["schemas"]["FieldOut"][];
        };
        /** LinkTypeOut */
        LinkTypeOut: {
            /** Key */
            key: string;
            /** Module */
            module: string;
            /** User Defined */
            user_defined: boolean;
            /** Label */
            label: string;
            /** Inverse Label */
            inverse_label: string | null;
            /** Description */
            description: string;
            /** Source Kinds */
            source_kinds: string[] | "*";
            /** Target Kinds */
            target_kinds: string[] | "*";
            /** Symmetric */
            symmetric: boolean;
            /**
             * Temporal
             * @enum {string}
             */
            temporal: "never" | "optional" | "required";
            /**
             * Unique
             * @enum {string}
             */
            unique: "none" | "per_pair" | "per_pair_per_period";
            /** Max Targets Per Source */
            max_targets_per_source: number | null;
            /** Max Sources Per Target */
            max_sources_per_target: number | null;
            /** Data Schema */
            data_schema: {
                [key: string]: unknown;
            } | null;
            graph: components["schemas"]["GraphStyleOut"];
            /** Archived */
            archived: boolean;
        };
        /** MetaResponse */
        MetaResponse: {
            /** App Version */
            app_version: string;
            /** Api Version */
            api_version: string;
            /** Read Only */
            read_only: boolean;
            /** Exposed Vaults */
            exposed_vaults: string[];
            /** Features */
            features: string[];
        };
        /** MigrationResponse */
        MigrationResponse: {
            vault: components["schemas"]["Vault"];
            /** From Revision */
            from_revision: string | null;
            /** To Revision */
            to_revision: string;
            /**
             * Backup
             * @description The pre-migration backup; null if nothing changed.
             */
            backup: string | null;
        };
        /** ModuleState */
        ModuleState: {
            /** Id */
            id: string;
            /** Name */
            name: string;
            /** Description */
            description: string;
            /** Depends On */
            depends_on: string[];
            /** Default Enabled */
            default_enabled: boolean;
            /** Enabled */
            enabled: boolean;
        };
        /** ModuleUpdate */
        ModuleUpdate: {
            /** Enabled */
            enabled: boolean;
            /**
             * Cascade
             * @default false
             */
            cascade: boolean;
        };
        /** ModuleUpdateResponse */
        ModuleUpdateResponse: {
            /** Enabled */
            enabled: string[];
            /** Disabled */
            disabled: string[];
            /** Modules */
            modules: components["schemas"]["ModuleState"][];
        };
        /**
         * Problem
         * @description Body of every error response.
         */
        Problem: {
            /** Type */
            type: string;
            /** Title */
            title: string;
            /** Status */
            status: number;
            /** Detail */
            detail: string;
            /** Code */
            code: string;
            /** Errors */
            errors?: components["schemas"]["ProblemErrorItem"][] | null;
            /** Context */
            context?: {
                [key: string]: unknown;
            } | null;
        };
        /** ProblemErrorItem */
        ProblemErrorItem: {
            /** Path */
            path: string;
            /** Code */
            code: string;
            /** Message */
            message: string;
        };
        /** QuickFixOut */
        QuickFixOut: {
            /** Id */
            id: string;
            /** Title */
            title: string;
        };
        /**
         * Registry
         * @description Everything the generic UI is generated from, for this vault's enabled modules.
         */
        Registry: {
            /** Kinds */
            kinds: components["schemas"]["KindOut"][];
            /** Field Types */
            field_types: components["schemas"]["FieldTypeOut"][];
            /** Link Types */
            link_types: components["schemas"]["LinkTypeOut"][];
            /** Modules */
            modules: components["schemas"]["ModuleState"][];
            /** Consistency Rules */
            consistency_rules: components["schemas"]["RuleOut"][];
        };
        /** RuleOut */
        RuleOut: {
            /** Id */
            id: string;
            /** Owner */
            owner: string;
            /** Title */
            title: string;
            /** Description */
            description: string;
            /**
             * Category
             * @enum {string}
             */
            category: "structural" | "narrative" | "advanced_time" | "module";
            /**
             * Default Severity
             * @enum {string}
             */
            default_severity: "off" | "warning" | "error";
            /** Configurable */
            configurable: boolean;
            /** Triggers */
            triggers: components["schemas"]["TriggerOut"][];
            /** Quick Fixes */
            quick_fixes: components["schemas"]["QuickFixOut"][];
        };
        SortKey: string;
        TagName: string;
        /** TagOut */
        TagOut: {
            /** Id */
            id: string;
            /** Name */
            name: string;
            /** Color */
            color: string | null;
        };
        /** TriggerOut */
        TriggerOut: {
            /**
             * Kind
             * @enum {string}
             */
            kind: "record" | "link_type" | "field";
            /** Key */
            key: string;
        };
        /**
         * Vault
         * @description A vault. ``modified_at`` is derived from its files' modification times.
         */
        Vault: {
            /** Id */
            id: string;
            /** Name */
            name: string;
            /** Folder */
            folder: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Created By App Version */
            created_by_app_version: string;
            /**
             * Modified At
             * Format: date-time
             */
            modified_at: string;
            /** Published */
            published: boolean;
            schema_status: components["schemas"]["VaultSchemaStatus"];
        };
        /** VaultCreate */
        VaultCreate: {
            name: components["schemas"]["VaultName"];
        };
        /**
         * VaultList
         * @description ``items``: most recently modified first, ties by name (case-insensitive).
         */
        VaultList: {
            /** Items */
            items: components["schemas"]["Vault"][];
            /** Problems */
            problems: components["schemas"]["VaultProblem"][];
        };
        VaultName: string;
        /**
         * VaultProblem
         * @description A folder in ``vaults/`` that can't be opened (listed so it doesn't look deleted).
         */
        VaultProblem: {
            /** Folder */
            folder: string;
            code: components["schemas"]["VaultProblemCode"];
            /** Detail */
            detail: string;
            /** Vault Id */
            vault_id?: string | null;
            /** Name */
            name?: string | null;
        };
        /** @enum {string} */
        VaultProblemCode: "folder_name_invalid" | "manifest_invalid" | "format_newer_than_app" | "duplicate_id";
        /** @enum {string} */
        VaultSchemaState: "current" | "needs_migration" | "newer_than_app" | "migration_failed" | "database_unreadable";
        /**
         * VaultSchemaStatus
         * @description The vault database's migration state. ``needs_migration``: ``POST /vaults/{v}/migrate``
         *     upgrades it (shown when ``LORE_AUTO_MIGRATE=false``).
         */
        VaultSchemaStatus: {
            state: components["schemas"]["VaultSchemaState"];
            /** Revision */
            revision: string | null;
            /** Head */
            head: string;
        };
        /** VaultUpdate */
        VaultUpdate: {
            name: components["schemas"]["VaultName"];
        };
        /** @enum {string} */
        Visibility: "public" | "spoiler" | "private";
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    system_health: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
            /** @description Problem */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
        };
    };
    system_meta: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MetaResponse"];
                };
            };
            /** @description Problem */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
        };
    };
    vaults_list: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["VaultList"];
                };
            };
            /** @description Problem */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
        };
    };
    vaults_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["VaultCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Vault"];
                };
            };
            /** @description Problem */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
        };
    };
    vaults_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Vault id (UUID). */
                vault_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Vault"];
                };
            };
            /** @description Problem */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
        };
    };
    vaults_delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Vault id (UUID). */
                vault_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Problem */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
        };
    };
    vaults_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Vault id (UUID). */
                vault_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["VaultUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Vault"];
                };
            };
            /** @description Problem */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
        };
    };
    vaults_migrate: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Vault id (UUID). */
                vault_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MigrationResponse"];
                };
            };
            /** @description Problem */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
        };
    };
    registry_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Vault id (UUID). */
                vault_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Registry"];
                };
            };
            /** @description Problem */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
        };
    };
    modules_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Module id. */
                module_id: string;
                /** @description Vault id (UUID). */
                vault_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ModuleUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ModuleUpdateResponse"];
                };
            };
            /** @description Problem */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
        };
    };
    entities_create: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Vault id (UUID). */
                vault_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["EntityCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EntityWriteResult"];
                };
            };
            /** @description Problem */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
        };
    };
    entities_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Entity id. */
                entity_id: string;
                /** @description Vault id (UUID). */
                vault_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EntityOut"];
                };
            };
            /** @description Problem */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
        };
    };
    entities_delete: {
        parameters: {
            query?: {
                /** @description Delete permanently (only entities already in the trash). */
                purge?: boolean;
            };
            header?: never;
            path: {
                /** @description Entity id. */
                entity_id: string;
                /** @description Vault id (UUID). */
                vault_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EntityDeleteResult"];
                };
            };
            /** @description Problem */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
        };
    };
    entities_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Entity id. */
                entity_id: string;
                /** @description Vault id (UUID). */
                vault_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["EntityUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EntityWriteResult"];
                };
            };
            /** @description Problem */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
        };
    };
    entities_restore: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Entity id. */
                entity_id: string;
                /** @description Vault id (UUID). */
                vault_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EntityWriteResult"];
                };
            };
            /** @description Problem */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
        };
    };
}
