/**
 * Calendar ticks for a timeline viewport (chronology-engine.md §12).
 *
 * For each regime's validity interval inside the viewport, the first (level, multiple) whose
 * estimated spacing (from the level's mean unit length) reaches `minSpacingPx` is chosen, from
 * fine to coarse: base units (1, 2, 5 × 10^k, below the finest level), levels with a fixed number
 * of regular children per parent (divisors of that number among 1, 2, 3, 4, 5, 6, 10, 12, 15, 20,
 * 30), variable levels (1, 2, 3, 6) and the top level (1, 2, 5 × 10^k for any `k`). Ticks are then
 * generated by stepping ordinals aligned to the multiple, so nothing iterates over units outside
 * the viewport. If more than `maxTicks` result, the next multiple is tried.
 *
 * Product decisions (2026-10-03): year multiples align on **era years** within each era (calendars
 * without eras use astronomical years), labeled like formatted years ("10 BC", "AD 2020"), and
 * era starts are major ticks. At multiple 1, intercalary units get ticks too (named: "Midyear's
 * Day"). Major ticks are the boundaries of the next coarser level (for years, the next power of
 * ten) labeled with the calendar's format at that precision ("March 2024"); minor ticks have short
 * labels (`shortLabel`). Base-unit ticks show the offset in the finest unit ("+30 s"). Year labels
 * in scientific notation keep the digits that tell ticks apart; minor ones that would need more
 * than 8 show the years since the preceding major tick ("+2").
 *
 * Everything is `bigint`; spacing comparisons use the viewport width in 1/1024 px.
 */
import {
  type CompiledCalendar,
  type CompiledEra,
  type CompiledRegime,
  defined,
} from '../calendar/compiled'
import { eraAt } from '../calendar/eras'
import { BASE, formatDate, shortLabel } from '../calendar/formatting'
import {
  REGULAR,
  countedPosition,
  fromCountedOrdinal,
  unitBounds,
  unitsPerPeriod,
} from '../calendar/units'
import { floorMod, formatInteger } from '../numbers'
import type { Viewport } from './viewport'

export interface Tick {
  readonly t: bigint
  readonly label: string
  /** Level id, or `base` for base-unit ticks. */
  readonly level: string
  /** The tick's step in units of its level. */
  readonly multiple: bigint
}

export interface Ticks {
  readonly major: readonly Tick[]
  /** Minor ticks; none coincides with a major tick. */
  readonly minor: readonly Tick[]
}

export interface TickOptions {
  /** Smallest estimated distance between minor ticks (default 64). */
  readonly minSpacingPx?: number
  /** Most ticks returned, major and minor together (default 100). */
  readonly maxTicks?: number
}

/** Multiples of levels with a fixed number of children per parent (divisors of that number). */
const NICE = [1n, 2n, 3n, 4n, 5n, 6n, 10n, 12n, 15n, 20n, 30n]
/** Multiples of levels whose parents hold varying numbers of children. */
const VARIABLE = [1n, 2n, 3n, 6n]
/** Minor year labels needing more significant digits than this show their offset from the
 * preceding major tick instead ("+2"; product decision, 2026-10-03). */
const MAX_DIGITS = 8
/** The finest "level": base units. */
const BASE_LEVEL = -1

/** The tick budget ran out: try the next multiple. */
class Overflow extends Error {}

interface Choice {
  /** Level index, or `BASE_LEVEL`. */
  readonly level: number
  readonly multiple: bigint
}

class Budget {
  readonly minor = new Map<bigint, Tick>()
  readonly major = new Map<bigint, Tick>()

  constructor(readonly limit: number) {}

  add(target: Map<bigint, Tick>, tick: Tick): void {
    target.set(tick.t, tick) // the same moment twice (an era start on an aligned year) counts once
    if (this.minor.size + this.major.size > this.limit) throw new Overflow()
  }
}

/** `[a, b)`: the part of the viewport where one regime is in force. */
interface Segment {
  readonly regime: CompiledRegime
  readonly a: bigint
  readonly b: bigint
}

function segments(calendar: CompiledCalendar, start: bigint, end: bigint): Segment[] {
  const found: Segment[] = []
  calendar.regimes.forEach((regime, i) => {
    const from = regime.index === 0 ? null : regime.startsAt
    const next = calendar.regimes[i + 1]?.startsAt ?? null
    const a = from !== null && from > start ? from : start
    const b = next !== null && next < end ? next : end
    if (a < b) found.push({ regime, a, b })
  })
  return found
}

/**
 * §12 `ticks`: the major and minor ticks of `calendar` in the viewport `[start, start + span)`,
 * sorted by moment. Never more than `maxTicks` in all.
 */
export function ticks(calendar: CompiledCalendar, v: Viewport, options: TickOptions = {}): Ticks {
  const minSpacing = BigInt(Math.max(1, Math.round((options.minSpacingPx ?? 64) * 1024)))
  const maxTicks = Math.max(1, Math.floor(options.maxTicks ?? 100))
  const width = Number.isFinite(v.widthPx) ? BigInt(Math.round(v.widthPx * 1024)) : 0n
  if (width <= 0n) throw new RangeError(`the viewport width must be positive: ${v.widthPx}`)
  const major: Tick[] = []
  const minor: Tick[] = []
  const parts = segments(calendar, v.start, v.start + v.span)
  parts.forEach((part, i) => {
    const budget = Math.floor((maxTicks - major.length - minor.length) / (parts.length - i))
    const found = segmentTicks(calendar, part, v.span, width, minSpacing, budget)
    major.push(...found.major)
    minor.push(...found.minor)
  })
  return { major, minor }
}

function segmentTicks(
  calendar: CompiledCalendar,
  part: Segment,
  span: bigint,
  width: bigint,
  minSpacing: bigint,
  limit: number,
): Ticks {
  for (const choice of choices(calendar, part.regime, span, width, minSpacing, limit)) {
    const budget = new Budget(limit)
    try {
      generate(calendar, part, choice, budget)
    } catch (error) {
      if (error instanceof Overflow) continue
      throw error
    }
    const byTime = (a: Tick, b: Tick): number => (a.t < b.t ? -1 : 1)
    const major = [...budget.major.values()].sort(byTime)
    const minor = [...budget.minor.values()].filter((tick) => !budget.major.has(tick.t))
    return { major, minor: minor.sort(byTime) }
  }
  return { major: [], minor: [] } // a budget of 0 ticks
}

// --- choosing the level and multiple -------------------------------------------------------------

/** Mean unit length of `level` as `[base units, units]` per top-pattern period. */
function meanLength(calendar: CompiledCalendar, regime: CompiledRegime, level: number) {
  if (level === BASE_LEVEL) return [1n, 1n] as const
  const top = calendar.levels.length - 1
  return [regime.cycleLength, unitsPerPeriod(regime, level, top, REGULAR)] as const
}

/** The candidate multiples of a level below the top, ascending. */
function multiplesOf(regime: CompiledRegime, level: number): bigint[] {
  if (level === BASE_LEVEL) {
    const longest = [...regime.templates.values()]
      .filter((template) => template.level === 0)
      .reduce((most, template) => (template.length > most ? template.length : most), 0n)
    const found: bigint[] = []
    for (let power = 1n; power < longest; power *= 10n) {
      for (const step of [1n, 2n, 5n]) if (step * power < longest) found.push(step * power)
    }
    return found
  }
  const parents = [...regime.templates.values()].filter((t) => t.level === level + 1)
  const counts = new Set(
    parents.map((t) => (t.totalCount === t.regularCount ? t.regularCount : -1n)),
  )
  const [count] = counts
  if (counts.size !== 1 || count === undefined || count <= 0n) return VARIABLE
  return NICE.filter((n) => n === 1n || (n < count && count % n === 0n))
}

/** The smallest of 1, 2, 5 × 10^k that is `≥ n`. */
function niceAtLeast(n: bigint): bigint {
  if (n <= 1n) return 1n
  const power = 10n ** BigInt((n - 1n).toString().length - 1)
  for (const step of [1n, 2n, 5n, 10n]) if (step * power >= n) return step * power
  /* v8 ignore next */
  return 10n * power
}

/** The next of 1, 2, 5 × 10^k after `n` (itself one of them). */
function niceAfter(n: bigint): bigint {
  const digits = n.toString()
  const power = 10n ** BigInt(digits.length - 1)
  return digits.startsWith('1') ? 2n * power : digits.startsWith('2') ? 5n * power : 10n * power
}

/** Candidate choices from fine to coarse whose estimated spacing and count fit. */
function* choices(
  calendar: CompiledCalendar,
  regime: CompiledRegime,
  span: bigint,
  width: bigint,
  minSpacing: bigint,
  limit: number,
): Generator<Choice> {
  const top = calendar.levels.length - 1
  // spacing(m) = length · m · width / (units · span) ≥ minSpacing; count ≈ span · units / (length · m)
  const fits = (length: bigint, units: bigint, m: bigint): boolean =>
    length * m * width >= minSpacing * units * span && span * units <= BigInt(limit) * length * m
  for (let level = BASE_LEVEL; level < top; level++) {
    const [length, units] = meanLength(calendar, regime, level)
    if (units === 0n) continue
    for (const m of multiplesOf(regime, level)) {
      if (fits(length, units, m)) yield { level, multiple: m }
    }
  }
  const [length, units] = meanLength(calendar, regime, top)
  const bySpacing = (minSpacing * units * span + length * width - 1n) / (length * width)
  const byCount = (span * units + BigInt(limit) * length - 1n) / (BigInt(limit) * length)
  let m = niceAtLeast(bySpacing > byCount ? bySpacing : byCount)
  for (;;) {
    yield { level: top, multiple: m }
    m = niceAfter(m)
  }
}

// --- generating ----------------------------------------------------------------------------------

function generate(calendar: CompiledCalendar, part: Segment, choice: Choice, budget: Budget): void {
  const top = calendar.levels.length - 1
  if (choice.level === top) {
    years(calendar, part, choice.multiple, budget)
    return
  }
  const majorLevel = choice.level + 1
  const majorId = defined(calendar.levels[majorLevel])
  walk(calendar, part, majorLevel, (t) => {
    budget.add(budget.major, {
      t,
      label: formatDate(calendar, t, majorId),
      level: majorId,
      multiple: 1n,
    })
  })
  if (choice.level === BASE_LEVEL) {
    baseTicks(calendar, part, choice.multiple, budget)
  } else if (choice.multiple === 1n) {
    const levelId = defined(calendar.levels[choice.level])
    walk(calendar, part, choice.level, (t) => {
      const label = shortLabel(calendar, t, choice.level)
      budget.add(budget.minor, { t, label, level: levelId, multiple: 1n })
    })
  } else {
    alignedUnits(calendar, part, choice, budget)
  }
}

/** Every unit of `level` (intercalary ones included) starting in the segment. */
function walk(
  calendar: CompiledCalendar,
  part: Segment,
  level: number,
  visit: (t: bigint) => void,
) {
  const levelId = defined(calendar.levels[level])
  let { start, end } = unitBounds(calendar, part.a, levelId)
  if (start < part.a) start = end
  while (start < part.b) {
    visit(start)
    end = unitBounds(calendar, start, levelId).end
    start = end
  }
}

/** Regular units of a level whose ordinal is a multiple of `choice.multiple`. */
function alignedUnits(calendar: CompiledCalendar, part: Segment, choice: Choice, budget: Budget) {
  const top = calendar.levels.length - 1
  const levelId = defined(calendar.levels[choice.level])
  const [before, counted, start] = countedPosition(top, part.regime, part.a, choice.level, REGULAR)
  let ordinal = counted && start < part.a ? before + 1n : before
  ordinal += floorMod(-ordinal, choice.multiple)
  const regime = { regime: part.regime.id }
  for (;;) {
    const t = fromCountedOrdinal(calendar, levelId, ordinal, REGULAR, regime).start
    if (t >= part.b) return
    const label = shortLabel(calendar, t, choice.level)
    budget.add(budget.minor, { t, label, level: levelId, multiple: choice.multiple })
    ordinal += choice.multiple
  }
}

/** Base units inside each level-0 unit at offsets that are multiples of `multiple`. */
function baseTicks(calendar: CompiledCalendar, part: Segment, multiple: bigint, budget: Budget) {
  const levelId = defined(calendar.levels[0])
  let { start, end } = unitBounds(calendar, part.a, levelId)
  while (start < part.b) {
    const from = part.a > start ? part.a : start
    let t = start + ((from - start + multiple - 1n) / multiple) * multiple
    if (t === start) t += multiple
    for (; t < end && t < part.b; t += multiple) {
      budget.add(budget.minor, { t, label: shortLabel(calendar, t, BASE), level: BASE, multiple })
    }
    start = end
    end = unitBounds(calendar, start, levelId).end
  }
}

// --- years ---------------------------------------------------------------------------------------

/** Years aligned to `multiple` (era years within each era), with major ticks every next power of
 * ten and at era starts. */
function years(calendar: CompiledCalendar, part: Segment, multiple: bigint, budget: Budget) {
  const top = calendar.levels.length - 1
  const topId = defined(calendar.levels[top])
  const majorMultiple = 10n ** BigInt(multiple.toString().length)
  for (const [a, b, era] of eraParts(calendar, part)) {
    if (era !== null && era.start === a) {
      budget.add(budget.major, {
        t: a,
        label: formatDate(calendar, a, topId),
        level: topId,
        multiple,
      })
    }
    alignedYears(part.regime, a, b, era, majorMultiple, (t, n) => {
      const label = shortLabel(calendar, t, top, { significantDigits: digitsFor(n, majorMultiple) })
      budget.add(budget.major, { t, label, level: topId, multiple: majorMultiple })
    })
    alignedYears(part.regime, a, b, era, multiple, (t, n) => {
      let label: string
      if (digitsFor(n, multiple) > MAX_DIGITS) {
        // years after the preceding major tick (era years count down in backward eras)
        const offset = era?.backward ? floorMod(-n, majorMultiple) : floorMod(n, majorMultiple)
        label = `+${formatInteger(offset)}`
      } else {
        label = shortLabel(calendar, t, top, { significantDigits: digitsFor(n, multiple) })
      }
      budget.add(budget.minor, { t, label, level: topId, multiple })
    })
  }
}

/** Significant digits that tell multiples of `m` apart in scientific notation (`2 × 10^111`,
 * `6.32501 × 10^102`): the digits of `n` above the trailing zeros every multiple has. */
function digitsFor(n: bigint, m: bigint): number {
  return (n < 0n ? -n : n).toString().length - (m.toString().length - 1)
}

/** The segment split at era starts: `[a, b, era]` (`era` null without eras). */
function eraParts(
  calendar: CompiledCalendar,
  part: Segment,
): [bigint, bigint, CompiledEra | null][] {
  const cuts = calendar.eras
    .map((era) => era.start)
    .filter((t): t is bigint => t !== null && t > part.a && t < part.b)
  const bounds = [part.a, ...cuts, part.b]
  return bounds.slice(0, -1).map((a, i) => [a, defined(bounds[i + 1]), eraAt(calendar, a)])
}

/** Years starting in `[a, b)` whose number (era year, else astronomical) is a multiple of `m`. */
function alignedYears(
  regime: CompiledRegime,
  a: bigint,
  b: bigint,
  era: CompiledEra | null,
  m: bigint,
  visit: (t: bigint, n: bigint) => void,
) {
  let first = regime.yearOf(a)
  if (regime.yearStart(first) < a) first += 1n
  const last = regime.yearOf(b - 1n)
  if (first > last) return
  const number = (year: bigint): bigint => (era === null ? year : era.eraYear(year))
  const yearOf = (n: bigint): bigint => (era === null ? n : era.year(n))
  const [low, high] = [number(first), number(last)].sort((x, y) => (x < y ? -1 : x > y ? 1 : 0))
  for (let n = defined(low) + floorMod(-defined(low), m); n <= defined(high); n += m) {
    visit(regime.yearStart(yearOf(n)), n)
  }
}
