// Generates src/api/schema.gen.ts from the backend's OpenAPI document (frontend.md §5.2).
//   node scripts/gen-api.ts           write the file (`make gen`)
//   node scripts/gen-api.ts --check   fail if the committed file is stale (`make check-contract`)
import { execFileSync, spawnSync } from 'node:child_process'
import { existsSync, mkdtempSync, readFileSync, rmSync, writeFileSync } from 'node:fs'
import { tmpdir } from 'node:os'
import path from 'node:path'
import { fileURLToPath, pathToFileURL } from 'node:url'

import openapiTS, { astToString } from 'openapi-typescript'

const frontendDir = fileURLToPath(new URL('..', import.meta.url))
const backendDir = path.resolve(frontendDir, '../backend')
const target = path.join(frontendDir, 'src/api/schema.gen.ts')
const relativeTarget = path.relative(process.cwd(), target)

const HEADER = `// Generated by \`make gen\` (frontend/scripts/gen-api.ts) from the backend's OpenAPI document.
// Do not edit by hand: change the backend models, then run \`make gen\` and commit this file.

`

async function generate(): Promise<string> {
  const tmp = mkdtempSync(path.join(tmpdir(), 'lore-openapi-'))
  try {
    const document = path.join(tmp, 'openapi.json')
    execFileSync('uv', ['run', '--quiet', 'lore', 'openapi', '--out', document], {
      cwd: backendDir,
      stdio: 'inherit',
    })
    const ast = await openapiTS(pathToFileURL(document))
    return HEADER + astToString(ast)
  } finally {
    rmSync(tmp, { recursive: true, force: true })
  }
}

function check(generated: string): boolean {
  const committed = existsSync(target) ? readFileSync(target, 'utf8') : null
  if (committed === generated) return true

  console.error(
    `${relativeTarget} is out of date with the backend's OpenAPI document.\n` +
      'Run `make gen` and commit the result (never edit generated files by hand).\n',
  )
  if (committed !== null) {
    const tmp = mkdtempSync(path.join(tmpdir(), 'lore-openapi-'))
    try {
      const fresh = path.join(tmp, 'schema.gen.ts')
      writeFileSync(fresh, generated)
      spawnSync('git', ['--no-pager', 'diff', '--no-index', '--stat', '--', target, fresh], {
        stdio: 'inherit',
      })
    } finally {
      rmSync(tmp, { recursive: true, force: true })
    }
  }
  return false
}

const generated = await generate()
if (process.argv.includes('--check')) {
  if (!check(generated)) process.exit(1)
  console.log(`${relativeTarget} is up to date.`)
} else {
  writeFileSync(target, generated)
  console.log(`wrote ${relativeTarget}`)
}
