// Generates, from spec/chronology/schema/bundle.json (chronology-engine.md §1):
//   src/schema.gen.ts           the chronology document types
//   src/calendar-schema.gen.ts  the JSON Schema of calendar definitions and compile contexts, which
//                               `validateCalendar` checks raw documents against (§11)
// The bundle itself is exported from the Python models by `lore chronology export-schemas`.
//   node scripts/gen-schema.ts           write the files (`make gen`)
//   node scripts/gen-schema.ts --check   fail if a committed file is stale (`make check-chronology`)
import { spawnSync } from 'node:child_process'
import { existsSync, mkdtempSync, readFileSync, rmSync, writeFileSync } from 'node:fs'
import { tmpdir } from 'node:os'
import path from 'node:path'
import { fileURLToPath } from 'node:url'

import { compile, type JSONSchema } from 'json-schema-to-typescript'

const packageDir = fileURLToPath(new URL('..', import.meta.url))
const bundlePath = path.resolve(packageDir, '../../spec/chronology/schema/bundle.json')
const typesTarget = path.join(packageDir, 'src/schema.gen.ts')
const schemaTarget = path.join(packageDir, 'src/calendar-schema.gen.ts')

const HEADER = `// Generated by \`make gen\` (packages/chronology/scripts/gen-schema.ts) from
// spec/chronology/schema/bundle.json, which is exported from backend/src/lore/chronology/schema.py.
// Do not edit by hand: change the Pydantic models, then run \`make gen\` and commit this file.
`

/** The documents `validateCalendar` checks; their definitions are kept with everything they use. */
const VALIDATED_ROOTS = ['CalendarDefinition', 'CompileContext']
/** Annotation keywords that don't affect validation (dropped to keep the bundle small). */
const ANNOTATIONS = new Set(['$schema', 'title', 'description', 'default', 'examples'])

type Json = null | boolean | number | string | Json[] | { [key: string]: Json }

async function generateTypes(bundle: JSONSchema): Promise<string> {
  const body = await compile(bundle, 'ChronologySchemas', {
    bannerComment: '',
    additionalProperties: false,
    declareExternallyReferenced: true,
    enableConstEnums: false,
    strictIndexSignatures: true,
    unreachableDefinitions: true,
    format: true,
    style: { semi: false, singleQuote: true, printWidth: 100, trailingComma: 'all' },
  })
  return (
    HEADER +
    '// Integers are decimal strings here; engine code converts them to bigint.\n' +
    stripReferenceNotes(`\n${body}`)
  )
}

/** Drop json-schema-to-typescript's "This interface was referenced by …" notes (noise). */
function stripReferenceNotes(source: string): string {
  const note = /\n(\s*)\* This interface was referenced by [^\n]*\n\s*\* via the [^\n]*/g
  return source
    .replace(note, '')
    .replace(/\n(\s*)\*\n(\s*)\*\//g, '\n$2*/') // trailing blank comment line
    .replace(/\n\s*\/\*\*\n\s*\*\//g, '') // comments left empty
}

function generateValidationSchema(bundle: { $defs: Record<string, Json> }): string {
  const defs: Record<string, Json> = {}
  const visit = (node: Json): void => {
    if (Array.isArray(node)) {
      node.forEach(visit)
    } else if (node !== null && typeof node === 'object') {
      const ref = node.$ref
      if (typeof ref === 'string') addDefinition(ref.replace('#/$defs/', ''))
      Object.values(node).forEach(visit)
    }
  }
  const addDefinition = (name: string): void => {
    if (name in defs) return
    const definition = bundle.$defs[name]
    if (definition === undefined) throw new Error(`unknown definition ${name}`)
    defs[name] = stripAnnotations(definition)
    visit(definition)
  }
  VALIDATED_ROOTS.forEach(addDefinition)
  const sorted = Object.fromEntries(Object.entries(defs).sort(([a], [b]) => a.localeCompare(b)))
  return (
    HEADER +
    '// The JSON Schema definitions of calendar definitions and compile contexts, without\n' +
    '// annotations. `$ref`s point into this object (`#/$defs/<name>`).\n\n' +
    `export const CALENDAR_SCHEMA_DEFS: Readonly<Record<string, unknown>> = ${JSON.stringify(sorted, null, 2)}\n`
  )
}

/** Remove annotation keywords (never property names: those live under `properties`). */
function stripAnnotations(node: Json, inProperties = false): Json {
  if (Array.isArray(node)) return node.map((item) => stripAnnotations(item))
  if (node === null || typeof node !== 'object') return node
  return Object.fromEntries(
    Object.entries(node)
      .filter(([key]) => inProperties || !ANNOTATIONS.has(key))
      .map(([key, value]) => [
        key,
        stripAnnotations(value, !inProperties && (key === 'properties' || key === '$defs')),
      ]),
  )
}

function check(target: string, generated: string): boolean {
  const relative = path.relative(process.cwd(), target)
  const committed = existsSync(target) ? readFileSync(target, 'utf8') : null
  if (committed === generated) {
    console.log(`${relative} is up to date.`)
    return true
  }

  console.error(
    `${relative} is out of date with spec/chronology/schema/bundle.json.\n` +
      'Run `make gen` and commit the result (never edit generated files by hand).\n',
  )
  if (committed !== null) {
    const tmp = mkdtempSync(path.join(tmpdir(), 'lore-chronology-'))
    try {
      const fresh = path.join(tmp, path.basename(target))
      writeFileSync(fresh, generated)
      spawnSync('git', ['--no-pager', 'diff', '--no-index', '--stat', '--', target, fresh], {
        stdio: 'inherit',
      })
    } finally {
      rmSync(tmp, { recursive: true, force: true })
    }
  }
  return false
}

const bundle = JSON.parse(readFileSync(bundlePath, 'utf8')) as JSONSchema & {
  $defs: Record<string, Json>
}
const outputs: [string, string][] = [
  [typesTarget, await generateTypes(bundle)],
  [schemaTarget, generateValidationSchema(bundle)],
]
if (process.argv.includes('--check')) {
  const results = outputs.map(([target, generated]) => check(target, generated))
  if (!results.every(Boolean)) process.exit(1)
} else {
  for (const [target, generated] of outputs) {
    writeFileSync(target, generated)
    console.log(`wrote ${path.relative(process.cwd(), target)}`)
  }
}
