// Generates src/schema.gen.ts from spec/chronology/schema/bundle.json (chronology-engine.md §1).
// The bundle itself is exported from the Python models by `lore chronology export-schemas`.
//   node scripts/gen-schema.ts           write the file (`make gen`)
//   node scripts/gen-schema.ts --check   fail if the committed file is stale (`make check-chronology`)
import { spawnSync } from 'node:child_process'
import { existsSync, mkdtempSync, readFileSync, rmSync, writeFileSync } from 'node:fs'
import { tmpdir } from 'node:os'
import path from 'node:path'
import { fileURLToPath } from 'node:url'

import { compile, type JSONSchema } from 'json-schema-to-typescript'

const packageDir = fileURLToPath(new URL('..', import.meta.url))
const bundlePath = path.resolve(packageDir, '../../spec/chronology/schema/bundle.json')
const target = path.join(packageDir, 'src/schema.gen.ts')
const relativeTarget = path.relative(process.cwd(), target)

const HEADER = `// Generated by \`make gen\` (packages/chronology/scripts/gen-schema.ts) from
// spec/chronology/schema/bundle.json, which is exported from backend/src/lore/chronology/schema.py.
// Do not edit by hand: change the Pydantic models, then run \`make gen\` and commit this file.
// Integers are decimal strings here; engine code converts them to bigint.
`

async function generate(): Promise<string> {
  const schema = JSON.parse(readFileSync(bundlePath, 'utf8')) as JSONSchema
  const body = await compile(schema, 'ChronologySchemas', {
    bannerComment: '',
    additionalProperties: false,
    declareExternallyReferenced: true,
    enableConstEnums: false,
    strictIndexSignatures: true,
    unreachableDefinitions: true,
    format: true,
    style: { semi: false, singleQuote: true, printWidth: 100, trailingComma: 'all' },
  })
  return HEADER + stripReferenceNotes(`\n${body}`)
}

/** Drop json-schema-to-typescript's "This interface was referenced by …" notes (noise). */
function stripReferenceNotes(source: string): string {
  const note = /\n(\s*)\* This interface was referenced by [^\n]*\n\s*\* via the [^\n]*/g
  return source
    .replace(note, '')
    .replace(/\n(\s*)\*\n(\s*)\*\//g, '\n$2*/') // trailing blank comment line
    .replace(/\n\s*\/\*\*\n\s*\*\//g, '') // comments left empty
}

function check(generated: string): boolean {
  const committed = existsSync(target) ? readFileSync(target, 'utf8') : null
  if (committed === generated) return true

  console.error(
    `${relativeTarget} is out of date with spec/chronology/schema/bundle.json.\n` +
      'Run `make gen` and commit the result (never edit generated files by hand).\n',
  )
  if (committed !== null) {
    const tmp = mkdtempSync(path.join(tmpdir(), 'lore-chronology-'))
    try {
      const fresh = path.join(tmp, 'schema.gen.ts')
      writeFileSync(fresh, generated)
      spawnSync('git', ['--no-pager', 'diff', '--no-index', '--stat', '--', target, fresh], {
        stdio: 'inherit',
      })
    } finally {
      rmSync(tmp, { recursive: true, force: true })
    }
  }
  return false
}

const generated = await generate()
if (process.argv.includes('--check')) {
  if (!check(generated)) process.exit(1)
  console.log(`${relativeTarget} is up to date.`)
} else {
  writeFileSync(target, generated)
  console.log(`wrote ${relativeTarget}`)
}
