// Generated by `make gen` (packages/chronology/scripts/gen-schema.ts) from
// spec/chronology/schema/bundle.json, which is exported from backend/src/lore/chronology/schema.py.
// Do not edit by hand: change the Pydantic models, then run `make gen` and commit this file.
// The JSON Schema definitions of calendar definitions and compile contexts, without
// annotations. `$ref`s point into this object (`#/$defs/<name>`).

export const CALENDAR_SCHEMA_DEFS: Readonly<Record<string, unknown>> = {
  "AbsoluteAnchor": {
    "additionalProperties": false,
    "properties": {
      "kind": {
        "const": "absolute",
        "type": "string"
      },
      "t": {
        "maxLength": 1000,
        "pattern": "^(0|[1-9][0-9]*)$",
        "type": "string"
      }
    },
    "required": [
      "kind",
      "t"
    ],
    "type": "object"
  },
  "Alignment": {
    "additionalProperties": false,
    "properties": {
      "fields": {
        "maxProperties": 20,
        "minProperties": 1,
        "patternProperties": {
          "^[a-z][a-z0-9_]*$": {
            "maxLength": 1001,
            "pattern": "^(0|-?[1-9][0-9]*|[a-z][a-z0-9_-]*)$",
            "type": "string"
          }
        },
        "propertyNames": {
          "maxLength": 64
        },
        "type": "object"
      },
      "at": {
        "$ref": "#/$defs/TimePoint"
      }
    },
    "required": [
      "fields",
      "at"
    ],
    "type": "object"
  },
  "AllPredicate": {
    "additionalProperties": false,
    "properties": {
      "all": {
        "items": {
          "$ref": "#/$defs/Predicate"
        },
        "minItems": 1,
        "type": "array"
      }
    },
    "required": [
      "all"
    ],
    "type": "object"
  },
  "Anchor": {
    "discriminator": {
      "mapping": {
        "absolute": "#/$defs/AbsoluteAnchor",
        "calendar": "#/$defs/CalendarAnchor",
        "relative": "#/$defs/RelativeAnchor"
      },
      "propertyName": "kind"
    },
    "oneOf": [
      {
        "$ref": "#/$defs/AbsoluteAnchor"
      },
      {
        "$ref": "#/$defs/CalendarAnchor"
      },
      {
        "$ref": "#/$defs/RelativeAnchor"
      }
    ]
  },
  "AnyPredicate": {
    "additionalProperties": false,
    "properties": {
      "any": {
        "items": {
          "$ref": "#/$defs/Predicate"
        },
        "minItems": 1,
        "type": "array"
      }
    },
    "required": [
      "any"
    ],
    "type": "object"
  },
  "BaseDuration": {
    "additionalProperties": false,
    "properties": {
      "kind": {
        "const": "base",
        "type": "string"
      },
      "units": {
        "maxLength": 1001,
        "pattern": "^(0|-?[1-9][0-9]*)$",
        "type": "string"
      }
    },
    "required": [
      "kind",
      "units"
    ],
    "type": "object"
  },
  "BaseUnit": {
    "additionalProperties": false,
    "properties": {
      "singular": {
        "maxLength": 200,
        "minLength": 1,
        "type": "string"
      },
      "plural": {
        "maxLength": 200,
        "minLength": 1,
        "type": "string"
      },
      "abbr": {
        "maxLength": 200,
        "minLength": 1,
        "type": "string"
      }
    },
    "required": [
      "singular",
      "plural",
      "abbr"
    ],
    "type": "object"
  },
  "CalendarAnchor": {
    "additionalProperties": false,
    "properties": {
      "kind": {
        "const": "calendar",
        "type": "string"
      },
      "calendar_id": {
        "maxLength": 64,
        "pattern": "^[A-Za-z0-9][A-Za-z0-9_-]*$",
        "type": "string"
      },
      "fields": {
        "maxProperties": 20,
        "minProperties": 1,
        "patternProperties": {
          "^[a-z][a-z0-9_]*$": {
            "maxLength": 1001,
            "pattern": "^(0|-?[1-9][0-9]*|[a-z][a-z0-9_-]*)$",
            "type": "string"
          }
        },
        "propertyNames": {
          "maxLength": 64
        },
        "type": "object"
      },
      "era": {
        "anyOf": [
          {
            "maxLength": 64,
            "pattern": "^[a-z][a-z0-9_]*$",
            "type": "string"
          },
          {
            "type": "null"
          }
        ]
      },
      "regime": {
        "anyOf": [
          {
            "maxLength": 64,
            "pattern": "^[a-z][a-z0-9_-]*$",
            "type": "string"
          },
          {
            "type": "null"
          }
        ]
      }
    },
    "required": [
      "kind",
      "calendar_id",
      "fields"
    ],
    "type": "object"
  },
  "CalendarDefinition": {
    "additionalProperties": false,
    "properties": {
      "schema_version": {
        "const": 1,
        "type": "integer"
      },
      "levels": {
        "items": {
          "$ref": "#/$defs/Level"
        },
        "maxItems": 20,
        "minItems": 1,
        "type": "array"
      },
      "regimes": {
        "items": {
          "$ref": "#/$defs/Regime"
        },
        "maxItems": 100,
        "minItems": 1,
        "type": "array"
      },
      "eras": {
        "items": {
          "$ref": "#/$defs/Era"
        },
        "maxItems": 1000,
        "type": "array"
      },
      "overlays": {
        "items": {
          "$ref": "#/$defs/Overlay"
        },
        "maxItems": 100,
        "type": "array"
      },
      "formats": {
        "anyOf": [
          {
            "$ref": "#/$defs/Formats"
          },
          {
            "type": "null"
          }
        ]
      },
      "display": {
        "anyOf": [
          {
            "$ref": "#/$defs/DisplayOptions"
          },
          {
            "type": "null"
          }
        ]
      }
    },
    "required": [
      "schema_version",
      "levels",
      "regimes"
    ],
    "type": "object"
  },
  "CalendarDuration": {
    "additionalProperties": false,
    "properties": {
      "kind": {
        "const": "calendar",
        "type": "string"
      },
      "calendar_id": {
        "maxLength": 64,
        "pattern": "^[A-Za-z0-9][A-Za-z0-9_-]*$",
        "type": "string"
      },
      "amounts": {
        "maxProperties": 20,
        "minProperties": 1,
        "patternProperties": {
          "^[a-z][a-z0-9_]*$": {
            "maxLength": 1000,
            "pattern": "^(0|[1-9][0-9]*)$",
            "type": "string"
          }
        },
        "propertyNames": {
          "maxLength": 64
        },
        "type": "object"
      },
      "sign": {
        "enum": [
          1,
          -1
        ],
        "type": "integer"
      }
    },
    "required": [
      "kind",
      "calendar_id",
      "amounts",
      "sign"
    ],
    "type": "object"
  },
  "CompileContext": {
    "additionalProperties": false,
    "properties": {
      "calendar_id": {
        "anyOf": [
          {
            "maxLength": 64,
            "pattern": "^[A-Za-z0-9][A-Za-z0-9_-]*$",
            "type": "string"
          },
          {
            "type": "null"
          }
        ]
      },
      "base_unit": {
        "$ref": "#/$defs/BaseUnit"
      },
      "dimension_duration": {
        "maxLength": 1000,
        "pattern": "^[1-9][0-9]*$",
        "type": "string"
      },
      "resolved": {
        "patternProperties": {
          "^(/[^/]*)*$": {
            "maxLength": 1000,
            "pattern": "^(0|[1-9][0-9]*)$",
            "type": "string"
          }
        },
        "type": "object"
      }
    },
    "required": [
      "base_unit",
      "dimension_duration"
    ],
    "type": "object"
  },
  "Cycle": {
    "additionalProperties": false,
    "properties": {
      "id": {
        "maxLength": 64,
        "pattern": "^[a-z][a-z0-9_]*$",
        "type": "string"
      },
      "level": {
        "maxLength": 64,
        "pattern": "^[a-z][a-z0-9_]*$",
        "type": "string"
      },
      "length": {
        "maximum": 1000000,
        "minimum": 1,
        "type": "integer"
      },
      "names": {
        "anyOf": [
          {
            "items": {
              "maxLength": 200,
              "minLength": 1,
              "type": "string"
            },
            "maxItems": 1000000,
            "type": "array"
          },
          {
            "type": "null"
          }
        ]
      },
      "abbrs": {
        "anyOf": [
          {
            "items": {
              "maxLength": 200,
              "minLength": 1,
              "type": "string"
            },
            "maxItems": 1000000,
            "type": "array"
          },
          {
            "type": "null"
          }
        ]
      },
      "number_start": {
        "maximum": 1000000,
        "minimum": 0,
        "type": "integer"
      },
      "mode": {
        "anyOf": [
          {
            "const": "continuous",
            "type": "string"
          },
          {
            "$ref": "#/$defs/ResetMode"
          }
        ]
      },
      "anchor": {
        "anyOf": [
          {
            "$ref": "#/$defs/CycleAnchor"
          },
          {
            "type": "null"
          }
        ]
      },
      "continue_from_previous_regime": {
        "type": "boolean"
      }
    },
    "required": [
      "id",
      "level",
      "length"
    ],
    "type": "object"
  },
  "CycleAnchor": {
    "additionalProperties": false,
    "properties": {
      "fields": {
        "anyOf": [
          {
            "maxProperties": 20,
            "minProperties": 1,
            "patternProperties": {
              "^[a-z][a-z0-9_]*$": {
                "maxLength": 1001,
                "pattern": "^(0|-?[1-9][0-9]*|[a-z][a-z0-9_-]*)$",
                "type": "string"
              }
            },
            "propertyNames": {
              "maxLength": 64
            },
            "type": "object"
          },
          {
            "type": "null"
          }
        ]
      },
      "index": {
        "maximum": 1000000,
        "minimum": 0,
        "type": "integer"
      }
    },
    "type": "object"
  },
  "CyclePattern": {
    "additionalProperties": false,
    "properties": {
      "kind": {
        "const": "cycle",
        "type": "string"
      },
      "templates": {
        "items": {
          "maxLength": 64,
          "pattern": "^[a-z][a-z0-9_]*$",
          "type": "string"
        },
        "maxItems": 1000000,
        "minItems": 1,
        "type": "array"
      },
      "start": {
        "maxLength": 1001,
        "pattern": "^(0|-?[1-9][0-9]*)$",
        "type": "string"
      }
    },
    "required": [
      "kind",
      "templates",
      "start"
    ],
    "type": "object"
  },
  "DefinitionAnchor": {
    "discriminator": {
      "mapping": {
        "absolute": "#/$defs/AbsoluteAnchor",
        "calendar": "#/$defs/CalendarAnchor",
        "local": "#/$defs/LocalAnchor",
        "relative": "#/$defs/RelativeAnchor"
      },
      "propertyName": "kind"
    },
    "oneOf": [
      {
        "$ref": "#/$defs/AbsoluteAnchor"
      },
      {
        "$ref": "#/$defs/CalendarAnchor"
      },
      {
        "$ref": "#/$defs/RelativeAnchor"
      },
      {
        "$ref": "#/$defs/LocalAnchor"
      }
    ]
  },
  "DefinitionTimePoint": {
    "additionalProperties": false,
    "properties": {
      "anchor": {
        "$ref": "#/$defs/DefinitionAnchor"
      },
      "precision": {
        "maxLength": 64,
        "pattern": "^[a-z][a-z0-9_]*$",
        "type": "string"
      },
      "approximate": {
        "type": "boolean"
      }
    },
    "required": [
      "anchor",
      "precision"
    ],
    "type": "object"
  },
  "DisplayOptions": {
    "additionalProperties": false,
    "properties": {
      "circa": {
        "maxLength": 50,
        "type": "string"
      },
      "digit_group": {
        "maxLength": 5,
        "type": "string"
      },
      "scientific_threshold": {
        "maximum": 1001,
        "minimum": 1,
        "type": "integer"
      },
      "significant_digits": {
        "maximum": 50,
        "minimum": 1,
        "type": "integer"
      },
      "range_separator": {
        "maxLength": 50,
        "type": "string"
      }
    },
    "type": "object"
  },
  "Duration": {
    "discriminator": {
      "mapping": {
        "base": "#/$defs/BaseDuration",
        "calendar": "#/$defs/CalendarDuration"
      },
      "propertyName": "kind"
    },
    "oneOf": [
      {
        "$ref": "#/$defs/BaseDuration"
      },
      {
        "$ref": "#/$defs/CalendarDuration"
      }
    ]
  },
  "Era": {
    "additionalProperties": false,
    "properties": {
      "id": {
        "maxLength": 64,
        "pattern": "^[a-z][a-z0-9_]*$",
        "type": "string"
      },
      "name": {
        "maxLength": 200,
        "minLength": 1,
        "type": "string"
      },
      "abbr": {
        "maxLength": 200,
        "minLength": 1,
        "type": "string"
      },
      "start": {
        "anyOf": [
          {
            "$ref": "#/$defs/DefinitionTimePoint"
          },
          {
            "type": "null"
          }
        ]
      },
      "numbering": {
        "$ref": "#/$defs/EraNumbering"
      },
      "abbr_position": {
        "enum": [
          "prefix",
          "suffix"
        ],
        "type": "string"
      }
    },
    "required": [
      "id",
      "name",
      "abbr",
      "numbering"
    ],
    "type": "object"
  },
  "EraNumbering": {
    "additionalProperties": false,
    "properties": {
      "direction": {
        "enum": [
          "forward",
          "backward"
        ],
        "type": "string"
      },
      "first": {
        "maxLength": 1001,
        "pattern": "^(0|-?[1-9][0-9]*)$",
        "type": "string"
      }
    },
    "required": [
      "direction",
      "first"
    ],
    "type": "object"
  },
  "FixedPattern": {
    "additionalProperties": false,
    "properties": {
      "kind": {
        "const": "fixed",
        "type": "string"
      },
      "template": {
        "maxLength": 64,
        "pattern": "^[a-z][a-z0-9_]*$",
        "type": "string"
      }
    },
    "required": [
      "kind",
      "template"
    ],
    "type": "object"
  },
  "Formats": {
    "additionalProperties": {
      "maxLength": 1000,
      "minLength": 1,
      "type": "string"
    },
    "properties": {
      "intercalary": {
        "patternProperties": {
          "^[a-z][a-z0-9_]*$": {
            "maxLength": 1000,
            "minLength": 1,
            "type": "string"
          }
        },
        "propertyNames": {
          "maxLength": 64
        },
        "type": "object"
      }
    },
    "type": "object"
  },
  "Level": {
    "additionalProperties": false,
    "properties": {
      "id": {
        "maxLength": 64,
        "pattern": "^[a-z][a-z0-9_]*$",
        "type": "string"
      },
      "label": {
        "maxLength": 200,
        "minLength": 1,
        "type": "string"
      },
      "plural": {
        "maxLength": 200,
        "minLength": 1,
        "type": "string"
      },
      "abbr": {
        "anyOf": [
          {
            "maxLength": 200,
            "minLength": 1,
            "type": "string"
          },
          {
            "type": "null"
          }
        ]
      },
      "numbering_start": {
        "maximum": 1000000,
        "minimum": 0,
        "type": "integer"
      },
      "default_template": {
        "anyOf": [
          {
            "maxLength": 64,
            "pattern": "^[a-z][a-z0-9_]*$",
            "type": "string"
          },
          {
            "type": "null"
          }
        ]
      }
    },
    "required": [
      "id",
      "label",
      "plural"
    ],
    "type": "object"
  },
  "LocalAnchor": {
    "additionalProperties": false,
    "properties": {
      "kind": {
        "const": "local",
        "type": "string"
      },
      "fields": {
        "maxProperties": 20,
        "minProperties": 1,
        "patternProperties": {
          "^[a-z][a-z0-9_]*$": {
            "maxLength": 1001,
            "pattern": "^(0|-?[1-9][0-9]*|[a-z][a-z0-9_-]*)$",
            "type": "string"
          }
        },
        "propertyNames": {
          "maxLength": 64
        },
        "type": "object"
      },
      "regime": {
        "anyOf": [
          {
            "maxLength": 64,
            "pattern": "^[a-z][a-z0-9_-]*$",
            "type": "string"
          },
          {
            "type": "null"
          }
        ]
      }
    },
    "required": [
      "kind",
      "fields"
    ],
    "type": "object"
  },
  "ModPredicate": {
    "additionalProperties": false,
    "properties": {
      "mod": {
        "maxLength": 1000,
        "pattern": "^[1-9][0-9]*$",
        "type": "string"
      },
      "eq": {
        "maxLength": 1000,
        "pattern": "^(0|[1-9][0-9]*)$",
        "type": "string"
      }
    },
    "required": [
      "mod",
      "eq"
    ],
    "type": "object"
  },
  "NamedChild": {
    "additionalProperties": false,
    "properties": {
      "id": {
        "maxLength": 64,
        "pattern": "^[a-z][a-z0-9_-]*$",
        "type": "string"
      },
      "template": {
        "maxLength": 64,
        "pattern": "^[a-z][a-z0-9_]*$",
        "type": "string"
      },
      "name": {
        "maxLength": 200,
        "minLength": 1,
        "type": "string"
      },
      "abbr": {
        "anyOf": [
          {
            "maxLength": 200,
            "minLength": 1,
            "type": "string"
          },
          {
            "type": "null"
          }
        ]
      },
      "intercalary": {
        "type": "boolean"
      },
      "cycle_excluded": {
        "items": {
          "maxLength": 64,
          "pattern": "^[a-z][a-z0-9_]*$",
          "type": "string"
        },
        "maxItems": 100,
        "type": "array"
      }
    },
    "required": [
      "id",
      "template",
      "name"
    ],
    "type": "object"
  },
  "NotPredicate": {
    "additionalProperties": false,
    "properties": {
      "not": {
        "$ref": "#/$defs/Predicate"
      }
    },
    "required": [
      "not"
    ],
    "type": "object"
  },
  "Overlay": {
    "additionalProperties": false,
    "properties": {
      "id": {
        "maxLength": 64,
        "pattern": "^[a-z][a-z0-9_]*$",
        "type": "string"
      },
      "name": {
        "maxLength": 200,
        "minLength": 1,
        "type": "string"
      },
      "period": {
        "$ref": "#/$defs/Rational"
      },
      "epoch": {
        "$ref": "#/$defs/DefinitionTimePoint"
      },
      "phases": {
        "items": {
          "$ref": "#/$defs/Phase"
        },
        "maxItems": 1000,
        "minItems": 1,
        "type": "array"
      }
    },
    "required": [
      "id",
      "name",
      "period",
      "epoch",
      "phases"
    ],
    "type": "object"
  },
  "Phase": {
    "additionalProperties": false,
    "properties": {
      "name": {
        "maxLength": 200,
        "minLength": 1,
        "type": "string"
      },
      "from": {
        "$ref": "#/$defs/Rational"
      }
    },
    "required": [
      "name",
      "from"
    ],
    "type": "object"
  },
  "Predicate": {
    "anyOf": [
      {
        "$ref": "#/$defs/ModPredicate"
      },
      {
        "$ref": "#/$defs/AllPredicate"
      },
      {
        "$ref": "#/$defs/AnyPredicate"
      },
      {
        "$ref": "#/$defs/NotPredicate"
      }
    ]
  },
  "Rational": {
    "additionalProperties": false,
    "properties": {
      "num": {
        "maxLength": 1001,
        "pattern": "^(0|-?[1-9][0-9]*)$",
        "type": "string"
      },
      "den": {
        "maxLength": 1000,
        "pattern": "^[1-9][0-9]*$",
        "type": "string"
      }
    },
    "required": [
      "num",
      "den"
    ],
    "type": "object"
  },
  "Regime": {
    "additionalProperties": false,
    "properties": {
      "id": {
        "maxLength": 64,
        "pattern": "^[a-z][a-z0-9_-]*$",
        "type": "string"
      },
      "name": {
        "maxLength": 200,
        "minLength": 1,
        "type": "string"
      },
      "starts_at": {
        "anyOf": [
          {
            "$ref": "#/$defs/DefinitionTimePoint"
          },
          {
            "type": "null"
          }
        ]
      },
      "templates": {
        "maxProperties": 500,
        "minProperties": 1,
        "patternProperties": {
          "^[a-z][a-z0-9_]*$": {
            "$ref": "#/$defs/Template"
          }
        },
        "propertyNames": {
          "maxLength": 64
        },
        "type": "object"
      },
      "top": {
        "$ref": "#/$defs/TopPattern"
      },
      "alignment": {
        "$ref": "#/$defs/Alignment"
      },
      "cycles": {
        "items": {
          "$ref": "#/$defs/Cycle"
        },
        "maxItems": 100,
        "type": "array"
      }
    },
    "required": [
      "id",
      "name",
      "templates",
      "top",
      "alignment"
    ],
    "type": "object"
  },
  "RelativeAnchor": {
    "additionalProperties": false,
    "properties": {
      "kind": {
        "const": "relative",
        "type": "string"
      },
      "ref": {
        "$ref": "#/$defs/SlotRef"
      },
      "offset": {
        "$ref": "#/$defs/Duration"
      }
    },
    "required": [
      "kind",
      "ref",
      "offset"
    ],
    "type": "object"
  },
  "ResetMode": {
    "additionalProperties": false,
    "properties": {
      "reset": {
        "maxLength": 64,
        "pattern": "^[a-z][a-z0-9_]*$",
        "type": "string"
      }
    },
    "required": [
      "reset"
    ],
    "type": "object"
  },
  "RulesPattern": {
    "additionalProperties": false,
    "properties": {
      "kind": {
        "const": "rules",
        "type": "string"
      },
      "default": {
        "type": "string",
        "maxLength": 64,
        "pattern": "^[a-z][a-z0-9_]*$"
      },
      "rules": {
        "items": {
          "$ref": "#/$defs/YearRule"
        },
        "maxItems": 1000,
        "type": "array"
      }
    },
    "required": [
      "kind",
      "default",
      "rules"
    ],
    "type": "object"
  },
  "RunChild": {
    "additionalProperties": false,
    "properties": {
      "run": {
        "$ref": "#/$defs/RunLayout"
      }
    },
    "required": [
      "run"
    ],
    "type": "object"
  },
  "RunLayout": {
    "additionalProperties": false,
    "properties": {
      "count": {
        "maxLength": 1000,
        "pattern": "^[1-9][0-9]*$",
        "type": "string"
      },
      "template": {
        "anyOf": [
          {
            "maxLength": 64,
            "pattern": "^[a-z][a-z0-9_]*$",
            "type": "string"
          },
          {
            "type": "null"
          }
        ]
      }
    },
    "required": [
      "count"
    ],
    "type": "object"
  },
  "SequenceChild": {
    "anyOf": [
      {
        "$ref": "#/$defs/NamedChild"
      },
      {
        "$ref": "#/$defs/RunChild"
      }
    ]
  },
  "SequenceTemplate": {
    "additionalProperties": false,
    "properties": {
      "level": {
        "maxLength": 64,
        "pattern": "^[a-z][a-z0-9_]*$",
        "type": "string"
      },
      "sequence": {
        "items": {
          "$ref": "#/$defs/SequenceChild"
        },
        "maxItems": 10000,
        "minItems": 1,
        "type": "array"
      }
    },
    "required": [
      "level",
      "sequence"
    ],
    "type": "object"
  },
  "SlotRef": {
    "additionalProperties": false,
    "properties": {
      "type": {
        "maxLength": 64,
        "pattern": "^[a-z][a-z0-9_]*(\\.[a-z][a-z0-9_]*)?$",
        "type": "string"
      },
      "id": {
        "maxLength": 64,
        "pattern": "^[A-Za-z0-9][A-Za-z0-9_-]*$",
        "type": "string"
      },
      "slot": {
        "maxLength": 200,
        "pattern": "^[a-z][a-z0-9_]*(:[A-Za-z0-9_.-]+)?$",
        "type": "string"
      },
      "occurrence": {
        "anyOf": [
          {
            "maxLength": 1001,
            "pattern": "^(0|[1-9][0-9]*)(\\.(0|[1-9][0-9]*))?$",
            "type": "string"
          },
          {
            "type": "null"
          }
        ]
      }
    },
    "required": [
      "type",
      "id",
      "slot"
    ],
    "type": "object"
  },
  "Template": {
    "anyOf": [
      {
        "$ref": "#/$defs/UniformTemplate"
      },
      {
        "$ref": "#/$defs/SequenceTemplate"
      }
    ]
  },
  "TimePoint": {
    "additionalProperties": false,
    "properties": {
      "anchor": {
        "$ref": "#/$defs/Anchor"
      },
      "precision": {
        "maxLength": 64,
        "pattern": "^[a-z][a-z0-9_]*$",
        "type": "string"
      },
      "approximate": {
        "type": "boolean"
      }
    },
    "required": [
      "anchor",
      "precision"
    ],
    "type": "object"
  },
  "TopPattern": {
    "additionalProperties": false,
    "properties": {
      "pattern": {
        "$ref": "#/$defs/YearPattern"
      },
      "exceptions": {
        "items": {
          "$ref": "#/$defs/YearException"
        },
        "maxItems": 100000,
        "type": "array"
      }
    },
    "required": [
      "pattern"
    ],
    "type": "object"
  },
  "UniformLayout": {
    "additionalProperties": false,
    "properties": {
      "count": {
        "maxLength": 1000,
        "pattern": "^[1-9][0-9]*$",
        "type": "string"
      },
      "template": {
        "anyOf": [
          {
            "maxLength": 64,
            "pattern": "^[a-z][a-z0-9_]*$",
            "type": "string"
          },
          {
            "type": "null"
          }
        ]
      }
    },
    "required": [
      "count"
    ],
    "type": "object"
  },
  "UniformTemplate": {
    "additionalProperties": false,
    "properties": {
      "level": {
        "maxLength": 64,
        "pattern": "^[a-z][a-z0-9_]*$",
        "type": "string"
      },
      "uniform": {
        "$ref": "#/$defs/UniformLayout"
      }
    },
    "required": [
      "level",
      "uniform"
    ],
    "type": "object"
  },
  "YearException": {
    "additionalProperties": false,
    "properties": {
      "year": {
        "maxLength": 1001,
        "pattern": "^(0|-?[1-9][0-9]*)$",
        "type": "string"
      },
      "template": {
        "maxLength": 64,
        "pattern": "^[a-z][a-z0-9_]*$",
        "type": "string"
      }
    },
    "required": [
      "year",
      "template"
    ],
    "type": "object"
  },
  "YearPattern": {
    "discriminator": {
      "mapping": {
        "cycle": "#/$defs/CyclePattern",
        "fixed": "#/$defs/FixedPattern",
        "rules": "#/$defs/RulesPattern"
      },
      "propertyName": "kind"
    },
    "oneOf": [
      {
        "$ref": "#/$defs/FixedPattern"
      },
      {
        "$ref": "#/$defs/CyclePattern"
      },
      {
        "$ref": "#/$defs/RulesPattern"
      }
    ]
  },
  "YearRule": {
    "additionalProperties": false,
    "properties": {
      "when": {
        "$ref": "#/$defs/Predicate"
      },
      "template": {
        "maxLength": 64,
        "pattern": "^[a-z][a-z0-9_]*$",
        "type": "string"
      }
    },
    "required": [
      "when",
      "template"
    ],
    "type": "object"
  }
}
