// Generated by `make gen` (packages/chronology/scripts/gen-schema.ts) from
// spec/chronology/schema/bundle.json, which is exported from backend/src/lore/chronology/schema.py.
// Do not edit by hand: change the Pydantic models, then run `make gen` and commit this file.
// Integers are decimal strings here; engine code converts them to bigint.

export type Anchor = AbsoluteAnchor | CalendarAnchor | RelativeAnchor
export type Duration = BaseDuration | CalendarDuration
export type EndSpec = TimePointEnd | DurationEnd | InstantEnd | EndOfTimeEnd | UnknownEnd
export type DefinitionAnchor = AbsoluteAnchor | CalendarAnchor | RelativeAnchor | LocalAnchor
export type Template = UniformTemplate | SequenceTemplate
export type SequenceChild = NamedChild | RunChild
export type YearPattern = FixedPattern | CyclePattern | RulesPattern
export type Predicate = ModPredicate | AllPredicate | AnyPredicate | NotPredicate
export type RecurrenceRule = CalendarRule | IntervalRule
export type PeriodFilter = ModFilter | InFilter | CycleFilter | AllFilter | AnyFilter | NotFilter
export type LevelSelector = ValuesSelector | CycleSelector | AllSelector
export type Limit = NeverLimit | CountLimit | UntilLimit

/**
 * Index of the top-level chronology types (generated; see spec/README.md).
 */
export interface ChronologySchemas {
  Rational?: Rational
  Anchor?: Anchor
  TimePoint?: TimePoint
  Duration?: Duration
  EndSpec?: EndSpec
  CalendarDefinition?: CalendarDefinition
  CompileContext?: CompileContext
  Preset?: Preset
  RecurrenceRule?: RecurrenceRule
  CorrespondenceDef?: CorrespondenceDef
}
/**
 * An exact rational ``num/den``, always normalized: gcd 1 and ``den > 0`` (time-model §2.4).
 */
export interface Rational {
  num: string
  den: string
}
/**
 * A moment given directly.
 */
export interface AbsoluteAnchor {
  kind: 'absolute'
  t: string
}
/**
 * A typed date in a calendar; resolves to the start of the unit at the precision.
 */
export interface CalendarAnchor {
  kind: 'calendar'
  calendar_id: string
  fields: {
    [k: string]: string | undefined
  }
  era?: string | null
  regime?: string | null
}
/**
 * A slot of another record plus an offset (which may be negative or zero).
 */
export interface RelativeAnchor {
  kind: 'relative'
  ref: SlotRef
  offset: Duration
}
/**
 * A referenceable time slot of a record (time-model §6).
 */
export interface SlotRef {
  type: string
  id: string
  slot: string
  occurrence?: string | null
}
/**
 * An exact, signed number of base units.
 */
export interface BaseDuration {
  kind: 'base'
  units: string
}
/**
 * Amounts of calendar units, applied by calendar arithmetic (chronology-engine §9).
 */
export interface CalendarDuration {
  kind: 'calendar'
  calendar_id: string
  amounts: {
    [k: string]: string | undefined
  }
  sign: 1 | -1
}
/**
 * An anchor plus precision and the circa flag (time-model §5.1).
 *
 * The member ``range`` is reserved for explicit uncertainty ranges and rejected in v1.
 */
export interface TimePoint {
  anchor: Anchor
  precision: string
  approximate?: boolean
}
export interface TimePointEnd {
  kind: 'time_point'
  time_point: TimePoint
}
export interface DurationEnd {
  kind: 'duration'
  duration: Duration
}
export interface InstantEnd {
  kind: 'instant'
}
export interface EndOfTimeEnd {
  kind: 'end_of_time'
}
export interface UnknownEnd {
  kind: 'unknown'
}
/**
 * A calendar definition, schema v1 (chronology-engine §3).
 */
export interface CalendarDefinition {
  schema_version: 1
  /**
   * @minItems 1
   * @maxItems 20
   */
  levels:
    | [Level]
    | [Level, Level]
    | [Level, Level, Level]
    | [Level, Level, Level, Level]
    | [Level, Level, Level, Level, Level]
    | [Level, Level, Level, Level, Level, Level]
    | [Level, Level, Level, Level, Level, Level, Level]
    | [Level, Level, Level, Level, Level, Level, Level, Level]
    | [Level, Level, Level, Level, Level, Level, Level, Level, Level]
    | [Level, Level, Level, Level, Level, Level, Level, Level, Level, Level]
    | [Level, Level, Level, Level, Level, Level, Level, Level, Level, Level, Level]
    | [Level, Level, Level, Level, Level, Level, Level, Level, Level, Level, Level, Level]
    | [Level, Level, Level, Level, Level, Level, Level, Level, Level, Level, Level, Level, Level]
    | [
        Level,
        Level,
        Level,
        Level,
        Level,
        Level,
        Level,
        Level,
        Level,
        Level,
        Level,
        Level,
        Level,
        Level,
      ]
    | [
        Level,
        Level,
        Level,
        Level,
        Level,
        Level,
        Level,
        Level,
        Level,
        Level,
        Level,
        Level,
        Level,
        Level,
        Level,
      ]
    | [
        Level,
        Level,
        Level,
        Level,
        Level,
        Level,
        Level,
        Level,
        Level,
        Level,
        Level,
        Level,
        Level,
        Level,
        Level,
        Level,
      ]
    | [
        Level,
        Level,
        Level,
        Level,
        Level,
        Level,
        Level,
        Level,
        Level,
        Level,
        Level,
        Level,
        Level,
        Level,
        Level,
        Level,
        Level,
      ]
    | [
        Level,
        Level,
        Level,
        Level,
        Level,
        Level,
        Level,
        Level,
        Level,
        Level,
        Level,
        Level,
        Level,
        Level,
        Level,
        Level,
        Level,
        Level,
      ]
    | [
        Level,
        Level,
        Level,
        Level,
        Level,
        Level,
        Level,
        Level,
        Level,
        Level,
        Level,
        Level,
        Level,
        Level,
        Level,
        Level,
        Level,
        Level,
        Level,
      ]
    | [
        Level,
        Level,
        Level,
        Level,
        Level,
        Level,
        Level,
        Level,
        Level,
        Level,
        Level,
        Level,
        Level,
        Level,
        Level,
        Level,
        Level,
        Level,
        Level,
        Level,
      ]
  /**
   * @minItems 1
   * @maxItems 100
   */
  regimes: [Regime, ...Regime[]]
  /**
   * @maxItems 1000
   */
  eras?: Era[]
  /**
   * @maxItems 100
   */
  overlays?: Overlay[]
  formats?: Formats | null
  display?: DisplayOptions | null
}
/**
 * One calendar level, fine → coarse (chronology-engine §3.2).
 */
export interface Level {
  id: string
  label: string
  plural: string
  abbr?: string | null
  /**
   * Number of the first regular child in its parent; ignored for the top level.
   */
  numbering_start?: number
  default_template?: string | null
}
/**
 * A complete calendar structure with its own epoch (chronology-engine §3.3).
 */
export interface Regime {
  id: string
  name: string
  starts_at?: DefinitionTimePoint | null
  templates: {
    [k: string]: Template | undefined
  }
  top: TopPattern
  alignment: Alignment
  /**
   * @maxItems 100
   */
  cycles?: Cycle[]
}
/**
 * A time point inside a calendar definition: may also use a ``local`` anchor (§3.10).
 */
export interface DefinitionTimePoint {
  anchor: DefinitionAnchor
  precision: string
  approximate?: boolean
}
/**
 * A date in the calendar being defined (astronomical year). Valid only inside definitions.
 */
export interface LocalAnchor {
  kind: 'local'
  fields: {
    [k: string]: string | undefined
  }
  regime?: string | null
}
/**
 * ``count`` identical children (base units for level 0).
 */
export interface UniformTemplate {
  level: string
  uniform: UniformLayout
}
export interface UniformLayout {
  count: string
  template?: string | null
}
/**
 * Explicit children (chronology-engine §3.4).
 */
export interface SequenceTemplate {
  level: string
  /**
   * @minItems 1
   * @maxItems 10000
   */
  sequence: [SequenceChild, ...SequenceChild[]]
}
/**
 * A named slot of a sequence template.
 */
export interface NamedChild {
  id: string
  template: string
  name: string
  abbr?: string | null
  intercalary?: boolean
  /**
   * @maxItems 100
   */
  cycle_excluded?: string[]
}
/**
 * ``count`` unnamed, numbered children.
 */
export interface RunChild {
  run: RunLayout
}
export interface RunLayout {
  count: string
  template?: string | null
}
/**
 * Which template each top-level unit (year) uses.
 */
export interface TopPattern {
  pattern: YearPattern
  /**
   * @maxItems 100000
   */
  exceptions?: YearException[]
}
export interface FixedPattern {
  kind: 'fixed'
  template: string
}
export interface CyclePattern {
  kind: 'cycle'
  /**
   * @minItems 1
   * @maxItems 1000000
   */
  templates: [string, ...string[]]
  start: string
}
export interface RulesPattern {
  kind: 'rules'
  default: string
  /**
   * @maxItems 1000
   */
  rules: YearRule[]
}
export interface YearRule {
  when: Predicate
  template: string
}
/**
 * ``Y mod mod == eq`` (floor mod).
 */
export interface ModPredicate {
  mod: string
  eq: string
}
export interface AllPredicate {
  /**
   * @minItems 1
   */
  all: [Predicate, ...Predicate[]]
}
export interface AnyPredicate {
  /**
   * @minItems 1
   */
  any: [Predicate, ...Predicate[]]
}
export interface NotPredicate {
  not: Predicate
}
export interface YearException {
  year: string
  template: string
}
/**
 * The start of the unit denoted by ``fields`` (astronomical year) happens at ``at``.
 */
export interface Alignment {
  fields: {
    [k: string]: string | undefined
  }
  at: TimePoint
}
/**
 * A parallel cycle such as a week (chronology-engine §3.7).
 */
export interface Cycle {
  id: string
  level: string
  length: number
  names?: string[] | null
  abbrs?: string[] | null
  /**
   * Stable value ids (one per index) that recurrence rules use instead of names (§3.7).
   */
  ids?: string[] | null
  number_start?: number
  mode?: 'continuous' | ResetMode
  anchor?: CycleAnchor | null
  continue_from_previous_regime?: boolean
}
export interface ResetMode {
  reset: string
}
export interface CycleAnchor {
  fields?: {
    [k: string]: string | undefined
  } | null
  index?: number
}
/**
 * A partition of time with its own year numbering (chronology-engine §3.8).
 */
export interface Era {
  id: string
  name: string
  abbr: string
  start?: DefinitionTimePoint | null
  numbering: EraNumbering
  abbr_position?: 'prefix' | 'suffix'
}
export interface EraNumbering {
  direction: 'forward' | 'backward'
  first: string
}
/**
 * An astronomical cycle that never affects date structure (chronology-engine §3.9).
 */
export interface Overlay {
  id: string
  name: string
  period: Rational
  epoch: DefinitionTimePoint
  /**
   * @minItems 1
   * @maxItems 1000
   */
  phases: [Phase, ...Phase[]]
}
export interface Phase {
  name: string
  from: Rational
}
/**
 * Format patterns by precision level id, plus ``intercalary`` overrides (§3.11).
 */
export interface Formats {
  intercalary?: {
    [k: string]: string | undefined
  }
  [k: string]:
    | string
    | {
        [k: string]: string | undefined
      }
    | undefined
}
export interface DisplayOptions {
  circa?: string
  digit_group?: string
  scientific_threshold?: number
  significant_digits?: number
  range_separator?: string
}
/**
 * Inputs to ``compile`` besides the definition (chronology-engine §4).
 */
export interface CompileContext {
  /**
   * Id of the calendar being compiled (detects alignments anchored in the calendar itself).
   */
  calendar_id?: string | null
  base_unit: BaseUnit
  dimension_duration: string
  /**
   * Resolved moments of every non-local time point, keyed by JSON pointer into the definition.
   */
  resolved?: {
    [k: string]: string | undefined
  }
}
export interface BaseUnit {
  singular: string
  plural: string
  abbr: string
}
/**
 * A preset calendar (``chronology-engine.md`` §13), instantiated per dimension.
 *
 * The definition uses a level ``second`` as level 0 (``uniform.count = 1``); its absolute time
 * points hold seconds after the **origin**, the moment the alignment unit starts.
 */
export interface Preset {
  id: string
  name: string
  description: string
  /**
   * What the origin is, e.g. "the start of 1 January AD 1".
   */
  origin: string
  requires: PresetRequirements
  definition: CalendarDefinition
}
export interface PresetRequirements {
  /**
   * The dimension must last at least this long after the origin (the latest absolute anchor).
   */
  duration_seconds: string
}
/**
 * An RRULE-like rule generalized to any calendar (recurrence §2).
 */
export interface CalendarRule {
  schema_version?: 1
  kind: 'calendar'
  calendar_id: string
  freq: LevelFreq | CycleFreq
  interval?: string
  /**
   * @maxItems 100
   */
  filters?: PeriodFilter[]
  select?: Selector | null
  missing?: 'skip' | 'constrain'
  time?: TimeOfDay | null
  limit: Limit
  /**
   * @maxItems 10000
   */
  exclusions?: Exclusion[]
}
export interface LevelFreq {
  level: string
}
export interface CycleFreq {
  cycle: string
}
export interface ModFilter {
  mod: string
  eq: string
  of?: 'number' | 'ordinal'
}
export interface InFilter {
  /**
   * @minItems 1
   * @maxItems 10000
   */
  in: [string, ...string[]]
}
export interface CycleFilter {
  cycle: string
  /**
   * @minItems 1
   * @maxItems 10000
   */
  in: [string, ...string[]]
}
export interface AllFilter {
  /**
   * @minItems 1
   */
  all: [PeriodFilter, ...PeriodFilter[]]
}
export interface AnyFilter {
  /**
   * @minItems 1
   */
  any: [PeriodFilter, ...PeriodFilter[]]
}
export interface NotFilter {
  not: PeriodFilter
}
/**
 * Positions inside a period, from the period's child level downward (recurrence §2.3).
 */
export interface Selector {
  /**
   * @minItems 1
   * @maxItems 20
   */
  path:
    | [LevelSelector]
    | [LevelSelector, LevelSelector]
    | [LevelSelector, LevelSelector, LevelSelector]
    | [LevelSelector, LevelSelector, LevelSelector, LevelSelector]
    | [LevelSelector, LevelSelector, LevelSelector, LevelSelector, LevelSelector]
    | [LevelSelector, LevelSelector, LevelSelector, LevelSelector, LevelSelector, LevelSelector]
    | [
        LevelSelector,
        LevelSelector,
        LevelSelector,
        LevelSelector,
        LevelSelector,
        LevelSelector,
        LevelSelector,
      ]
    | [
        LevelSelector,
        LevelSelector,
        LevelSelector,
        LevelSelector,
        LevelSelector,
        LevelSelector,
        LevelSelector,
        LevelSelector,
      ]
    | [
        LevelSelector,
        LevelSelector,
        LevelSelector,
        LevelSelector,
        LevelSelector,
        LevelSelector,
        LevelSelector,
        LevelSelector,
        LevelSelector,
      ]
    | [
        LevelSelector,
        LevelSelector,
        LevelSelector,
        LevelSelector,
        LevelSelector,
        LevelSelector,
        LevelSelector,
        LevelSelector,
        LevelSelector,
        LevelSelector,
      ]
    | [
        LevelSelector,
        LevelSelector,
        LevelSelector,
        LevelSelector,
        LevelSelector,
        LevelSelector,
        LevelSelector,
        LevelSelector,
        LevelSelector,
        LevelSelector,
        LevelSelector,
      ]
    | [
        LevelSelector,
        LevelSelector,
        LevelSelector,
        LevelSelector,
        LevelSelector,
        LevelSelector,
        LevelSelector,
        LevelSelector,
        LevelSelector,
        LevelSelector,
        LevelSelector,
        LevelSelector,
      ]
    | [
        LevelSelector,
        LevelSelector,
        LevelSelector,
        LevelSelector,
        LevelSelector,
        LevelSelector,
        LevelSelector,
        LevelSelector,
        LevelSelector,
        LevelSelector,
        LevelSelector,
        LevelSelector,
        LevelSelector,
      ]
    | [
        LevelSelector,
        LevelSelector,
        LevelSelector,
        LevelSelector,
        LevelSelector,
        LevelSelector,
        LevelSelector,
        LevelSelector,
        LevelSelector,
        LevelSelector,
        LevelSelector,
        LevelSelector,
        LevelSelector,
        LevelSelector,
      ]
    | [
        LevelSelector,
        LevelSelector,
        LevelSelector,
        LevelSelector,
        LevelSelector,
        LevelSelector,
        LevelSelector,
        LevelSelector,
        LevelSelector,
        LevelSelector,
        LevelSelector,
        LevelSelector,
        LevelSelector,
        LevelSelector,
        LevelSelector,
      ]
    | [
        LevelSelector,
        LevelSelector,
        LevelSelector,
        LevelSelector,
        LevelSelector,
        LevelSelector,
        LevelSelector,
        LevelSelector,
        LevelSelector,
        LevelSelector,
        LevelSelector,
        LevelSelector,
        LevelSelector,
        LevelSelector,
        LevelSelector,
        LevelSelector,
      ]
    | [
        LevelSelector,
        LevelSelector,
        LevelSelector,
        LevelSelector,
        LevelSelector,
        LevelSelector,
        LevelSelector,
        LevelSelector,
        LevelSelector,
        LevelSelector,
        LevelSelector,
        LevelSelector,
        LevelSelector,
        LevelSelector,
        LevelSelector,
        LevelSelector,
        LevelSelector,
      ]
    | [
        LevelSelector,
        LevelSelector,
        LevelSelector,
        LevelSelector,
        LevelSelector,
        LevelSelector,
        LevelSelector,
        LevelSelector,
        LevelSelector,
        LevelSelector,
        LevelSelector,
        LevelSelector,
        LevelSelector,
        LevelSelector,
        LevelSelector,
        LevelSelector,
        LevelSelector,
        LevelSelector,
      ]
    | [
        LevelSelector,
        LevelSelector,
        LevelSelector,
        LevelSelector,
        LevelSelector,
        LevelSelector,
        LevelSelector,
        LevelSelector,
        LevelSelector,
        LevelSelector,
        LevelSelector,
        LevelSelector,
        LevelSelector,
        LevelSelector,
        LevelSelector,
        LevelSelector,
        LevelSelector,
        LevelSelector,
        LevelSelector,
      ]
    | [
        LevelSelector,
        LevelSelector,
        LevelSelector,
        LevelSelector,
        LevelSelector,
        LevelSelector,
        LevelSelector,
        LevelSelector,
        LevelSelector,
        LevelSelector,
        LevelSelector,
        LevelSelector,
        LevelSelector,
        LevelSelector,
        LevelSelector,
        LevelSelector,
        LevelSelector,
        LevelSelector,
        LevelSelector,
        LevelSelector,
      ]
}
export interface ValuesSelector {
  level: string
  /**
   * @minItems 1
   * @maxItems 10000
   */
  values: [string, ...string[]]
}
export interface CycleSelector {
  level: string
  cycle: CycleMatch
}
export interface CycleMatch {
  id: string
  /**
   * @minItems 1
   * @maxItems 10000
   */
  values: [string, ...string[]]
  nth?: [string, ...string[]] | null
}
export interface AllSelector {
  level: string
  all: true
}
export interface TimeOfDay {
  fields: {
    [k: string]: string | undefined
  }
}
export interface NeverLimit {
  kind: 'never'
}
export interface CountLimit {
  kind: 'count'
  count: string
}
export interface UntilLimit {
  kind: 'until'
  until: TimePoint
}
/**
 * Skip occurrences starting in ``[from, to)``.
 */
export interface Exclusion {
  from: TimePoint
  to: TimePoint
  note?: string | null
}
/**
 * A fixed interval in base units, independent of calendars.
 */
export interface IntervalRule {
  schema_version?: 1
  kind: 'interval'
  every: string
  limit: Limit
  /**
   * @maxItems 10000
   */
  exclusions?: Exclusion[]
}
/**
 * How time in two dimensions corresponds (time-model §12.1).
 */
export interface CorrespondenceDef {
  extrapolation?: 'none' | 'rate'
  rate_before?: Rational | null
  rate_after?: Rational | null
  /**
   * @minItems 1
   * @maxItems 10000
   */
  points: [SyncPoint, ...SyncPoint[]]
}
/**
 * ``a`` in dimension A happens at the same time as ``b`` in dimension B.
 */
export interface SyncPoint {
  a: TimePoint
  b: TimePoint
}
